### ISSUE TITLE
import sys

### ISSUE THREAD

**Issue by nvdl** [FreeCAD/FreeCAD-render#1]
In "Render.py", "sys" is not imported.
Gives out error in FreeCAD 0.17 (master branch, pulled and compiled at April 19, 2018).

This fixes it:
import os,re,tempfile,FreeCAD,importlib,sys

**Comment by luzpaz** [comment]
@yorikvanhavre :point_up:

**Comment by yorikvanhavre** [comment]
Fixed in 1455f7a
