### ISSUE TITLE
Support YafaRay Renderer ?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#10]
> YafaRay is a free open-source montecarlo raytracing engine released under the LGPL 2.1 license. Raytracing is a rendering technique for generating realistic images by tracing the path of light through a 3D scene.

sweethome3d just announced: http://sweethome3d.com/support/forum/viewthread_thread,9678

Website: http://www.yafaray.org/  
Github: https://github.com/YafaRay/Core
It uses the LGPL 2.1 license 

Would there be interest to have this in FreeCAD-Render ?

**Comment by howetuft** [comment]
Hello,
I may close this issue. Yafaray is no more supported, no active development/developer (repository archived on github), and even the website is down (so, no documentation...).
On the other hand, we now have a bunch of renderers, so I wouldn't spend time on this one...
