### ISSUE TITLE
Cannot use blender's renderer

### ISSUE THREAD

**Issue by adrien-n** [FreeCAD/FreeCAD-render#101]
Hi,

I've tried to use cycles on debian but I'm having quite a lot of troubles.

I pointed to /usr/bin/blender since that's the only executable I can call and afaiu it should work. However the default parameter --samples is unrecognized but also hard-coded ones like --output. According to https://docs.blender.org/manual/en/latest/advanced/command_line/render.html the invocation should be very different. I'm not familiar with blender/cycles so I don't know if there's maybe different executables with different command-line interfaces; in any case on debian (testing), there doesn't seem to be something dedicated for cycles.

**Comment by yorikvanhavre** [comment]
The render workbench will not work with the Blender executable directly, unfortunately... It works with Cycles, not Blender itself (yet). You need to have a standalone version of Cycles, AFAIK at the moment the only way to obtain one is by compiling yourself. We should actually explain that better in the documentation.. I'll leave this issue open to remind myself

**Comment by howetuft** [comment]
Hello @adrien-n 
You may find some more information about _Cycles Standalone_ installation here: https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/EngineInstall.md#notes-on-installing-cycles-for-render-standalone-version

(@yorikvanhavre A few weeks ago, I wrote some documentation, including renderers installation, at the kind request of @luzpaz!)
