### ISSUE TITLE
Wrong normals for POV-Ray

### ISSUE THREAD

**Issue by furti** [FreeCAD/FreeCAD-render#11]
When rendering a simple cube with POV-Ray for me the normals are clearly wrong.

This is a image with the normals created by the POV-Ray Renderer:
![image](https://user-images.githubusercontent.com/2047555/64448951-23e4ea80-d0df-11e9-8728-4a32902818ea.png)

And this is the same cube but with the normal_vectors commented out
![image](https://user-images.githubusercontent.com/2047555/64448974-35c68d80-d0df-11e9-8c5a-808afed1dc57.png)

The one without normals is what i would expect. Is there a reason why normals are written?

Maybe it is because i used POV-Ray 3.7 for rendering.

FreeCAD Version used
```
OS: Windows 10 (10.0)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.17803 (Git)
Build type: Release
Branch: master
Hash: 89961a33d46063a43e9fb5b0308ca95d559eca94
Python version: 3.6.8
Qt version: 5.12.1
Coin version: 4.0.0a
OCC version: 7.3.0
Locale: German/Austria (de_AT)
```

**Comment by yorikvanhavre** [comment]
strange, I hadn't seen that before.. I suppose the normals are important for curved surfaces.. That's what allows for smooth rendering across triangles.
they are obtained from the mesh: https://github.com/FreeCAD/FreeCAD-render/blob/master/renderers/Povray.py#L98 we should check what's wrong, maybe there is a simple fix such as inverting them.. Oterwise we could simply add an option to disable them mabe

**Comment by justnope** [comment]
You need to get the normals from the facets and not the points themselves. Then use that normal for the three vertices in that facet.
```
    for facet in mesh.Facets:
        # write facet.Normal
```
Here's an example: https://github.com/justnope/FreeCAD-render/blob/d01bf176185558d4e75a801102d54c5ef311c33c/renderers/Appleseed.py#L197-L221

**Comment by furti** [comment]
Using the Face normals would indeed give sharp edges. But what about a sphere? When using the face normals the surface will not look smooth? In that case the point normals will be what the user wants.

So maybe we need to give the user the option to say if the object should be rendered smooth or not. And use the right normals based on the selection.

But this might fail for lets say a cylinder, where the top and bottom faces should have sharp edges, but the side faces should be rendered smooth.

**Comment by justnope** [comment]
That could be solved by using the crease angle.
If the normals of two adjacent faces are below the crease angle then they are considered smooth. It's not implemented in the mesh class but it's in shape.  I don't think it's currently stored somewhere but in the python console you can type:
`App.ActiveDocument.<objname>.Shape.writeInventor()`
In the list you'll see creaseAngle. To get the string with a different crease angle you can type:
`App.ActiveDocument.<objname>.Shape.writeInventor(Angle=0.15)`

**Comment by howetuft** [comment]
Solved.
