### ISSUE TITLE
Image clipping within FreeCAD UI

### ISSUE THREAD

**Issue by vectronic** [FreeCAD/FreeCAD-render#127]
Hello,

I'd like to report a rendered image clipping issue in the FreeCAD UI. I have set the rendered image size to larger than the default value i.e. in the screenshot it is 1200x1600. 

This occurs sometimes and I can't work out how to cause it, or better still prevent it....

Regardless of whether I select "1:1 scale" or "Fit image" I get the results attached:

* for "1:1 scale" it seems the right scale, but the image is cropped and there is no scrolling possible
* for "Fit image" the whole image is visible but it doesn't seem to fill the available window space

I have set an output file (attached) and you can see it does render to the correct required size.

I have also attached the FreeCAD file. 

--

OS: macOS 10.16
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24054 (Git)
Build type: Release
Branch: master
Hash: ed873038025277f220dfaa058599a0dfbb435835
Python version: 3.8.6
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/United Kingdom (en_GB)

<img width="1440" alt="1_1_scale" src="https://user-images.githubusercontent.com/32313864/109569204-f57f7a00-7adf-11eb-8e37-943cc7ef65c4.png">

![brick_4x2](https://user-images.githubusercontent.com/32313864/109569210-f7e1d400-7adf-11eb-9b7f-1d4b101e9f8b.png)

<img width="1440" alt="fit_image" src="https://user-images.githubusercontent.com/32313864/109569216-f9ab9780-7adf-11eb-9da7-67d1b821b69f.png">

[brick_4x2.FCStd.zip](https://github.com/FreeCAD/FreeCAD-render/files/6064884/brick_4x2.FCStd.zip)

**Comment by howetuft** [comment]
Hello,
Thanks for feedback! However, I think it is not a Render issue. Indeed, as you remarked, the output image (/Users/nick/Desktop/brick_4x2.png) is correctly sized when you open it in an external viewer. What seems wrong is the way FreeCAD reimport it in internal view port. So, I'm sorry to tell you that, but you should rather open an issue in FreeCAD...

**Comment by vectronic** [comment]
Understood. Thanks. Will do.
