### ISSUE TITLE
Render settings cycles

### ISSUE THREAD

**Issue by HaasNL2** [FreeCAD/FreeCAD-render#137]
Been digging around in the Blender files and testing out settings, currently already got huge improvements.
What I am still missing is: Exposure settings as these seem too low.
And how to enable noise filtering as this would reduce render times hugely. 

I have been digging true cycles source to find these settings:
https://developer.blender.org/diffusion/C/
Below settings come from this file:
https://developer.blender.org/diffusion/C/browse/master/src/render/integrator.cpp

I have the following settings:
```
<cycles>

    <!-- Camera -->
    <camera width="1920" height="1080" />

    <!--RaytracingCamera-->

    <!-- Integrator -->
    <integrator 
	aa_samples="2"
	ao_samples="100"
	mesh_light_samples="2"
	subsurface_samples="0"
	volume_samples="0"
	diffuse_samples="1"
	glossy_samples="1"
	transmission_samples="0"
	min_bounce="0"
 	max_bounce="8"
	max_diffuse_bounce="4"
	max_glossy_bounce="4"
	max_volume_bounce="0"
	max_transmission_bounce="0"
	sample_clamp_direct="1"
	sample_clamp_indirect="10"
	method="branched_path" 
	sample_all_lights_direct="true" 
	sample_all_lights_indirect="true"
	caustics_reflective="true"
	caustics_refractiv="true"
	seed="98"
	transparent_min_bounce="2"
	transparent_max_bounce="7"
	filter_glossy="1"
	sampling_pattern="sobol"
	/>
	    <!-- Background Shader -->
    <background>
        <background name="bg" strength="2.0" color="0.2, 0.2, 0.2" />
        <connect from="bg background" to="output surface" />
    </background>
	
    <!--RaytracingContent-->
	
</cycles>
```

**Comment by howetuft** [comment]
Good catch! A few comments:

- If you find Denoising settings, I'm really interested. I succeeded in having OIDN run perfectly with ospray renderer (and the result is really amazing), but not with the other renderers. Any knowledge welcome!
- There is also a Film node that could be involved in exposure and noise control. See here: https://developer.blender.org/diffusion/C/browse/master/src/render/film.cpp$367
- Be careful about caustics computation, it can be very time expensive. It should be used sparingly, IMHO.

**Comment by HaasNL2** [comment]
Got a reply from Cycles dev that denoising is not supported in stand alone.
https://devtalk.blender.org/t/how-to-use-the-open-image-denoiser/18143/2
We btw found a blend to xml script:
https://github.com/zhutq/cycles-xml-exporter

**Comment by howetuft** [comment]
Too bad for denoising (maybe in the future ? but I think this is not a priority for Blender devs...).
Thank you for the script, but IMHO our exporter is already more efficient.
I close the thread!
