### ISSUE TITLE
Pbrt v4 help to input

### ISSUE THREAD

**Issue by claudiomush** [FreeCAD/FreeCAD-render#143]
Hallo, I'd like to see a support to pbrt. Now with the v4 they have a gpu support that runs very fast. My try merging a triangulated mesh with a simple header from a pbrt example for lights and camera was amazing. I'm unable anyway to assign the proper materials to the proper subassemblies. I'd like to start to write at least an input file for pbrt from inside freecad. Grateful for any suggestion.
Best regards
![simple-denoise-small](https://user-images.githubusercontent.com/83174729/116000418-62028b00-a5f0-11eb-8cd7-0c4adb910564.png)

**Comment by luzpaz** [comment]
I assume this is the code repo for pbrt v4? https://github.com/mmp/pbrt-v4

**Comment by howetuft** [comment]
Hello @claudiomush,
Yes, we can add support for pbrt v4. pbrt input format does not seem to be documented, but there are a full bunch of examples here: https://github.com/mmp/pbrt-v4-scenes
Are you skilled in Python? If so, the right way to proceed is to create a plugin in this workbench (explained here: https://github.com/FreeCAD/FreeCAD-render/tree/master/renderers). I've just created a 'pbrt' branch for such a dev, if you want to push PRs.
If you don't feel like writing this code, I can do it but I'm a bit short in time at the moment...

**Comment by claudiomush** [comment]
Hallo, Yes that repo is correct. I've a modest skill in Python but I'm unable to catch info about to select one part of subassembly of my Freecad project. Where have I to get some examples to that? I would try from the Python shell of Freecad to write an input file for pbrt or I'm wrong to do so? Be patient please starting from zero is difficult.

**Comment by howetuft** [comment]
Hello,
Well, no offense intended, but I think you may be a bit short for writing an exporter. I'm gonna write the plugin, it just may take a few weeks, due to my present lack of time...
Just a drawback with pbrt-v4: unfortunately the dev decided to remove Disney shader support (which existed in v3...), while we use it quite intensively. The dev has not explained how to translate old v3 Disney material to new shaders, although the question is asked in an issue (https://github.com/mmp/pbrt-v4/issues/4). We may be able to find some kind of workaround, but the result may still be a little disappointing for this material.

**Comment by claudiomush** [comment]
Hallo, really I'm do "short" for writing an exporter, so no offense at all. Anyway I'd like to know the process, even if long and complex and this could be interesting not for me only. Thanks for any news and... progress. Where could I catch infos about "Disney"?

**Comment by howetuft** [comment]
The process to write an exporter (a "plugin") for FreeCAD Render is described [here](https://github.com/FreeCAD/FreeCAD-render/blob/master/renderers/README.md). You may also take advantage of looking at existing code for the already supported rendering engines, in `renderers` subdirectory [here](https://github.com/FreeCAD/FreeCAD-render/tree/master/renderers).

Disney shader is a versatile and artist-friendly material. You may find some info about it in the following links, for instance:

- [Blender documentation](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html)
- [Clarisse documentation](https://clarissewiki.com/4.0/disney-principled.html)
- [RenderMan documentation](https://renderman.pixar.com/resources/RenderMan_20/PxrDisney.html)
- [Primary paper](https://static1.squarespace.com/static/58586fa5ebbd1a60e7d76d3e/t/593a3afa46c3c4a376d779f6/1496988449807/s2012_pbs_disney_brdf_notes_v2.pdf) (tough material)

...but also by searching the web with 'Disney shader' keywords.

Good luck!

**Comment by claudiomush** [comment]
Following your suggestion I wrote inside my .FreeCad a template, actually void, and an icon, horrible indeed. For a renderer I modified the Luxcore.py which I believe close to Pbrt. My attempt was to write a not temporary input file for pbrt, without results at the time, just to verify what I'm doing. I think my binding was unable to launch pbrt as render, I'm no sure, but I'm trying.
Thanks for Disney, a new world of shaders for me.

**Comment by howetuft** [comment]
Hello,
Following our exchange, I've added a plugin for pbrt v4.
It does the job but please note that, from my point of view, it is not fully functional due to those several limitations from pbrt at the moment:
- No Disney material (quite surprising: it's been removed from v3 to v4!)
- No Sun-sky lighting support (there's a sort of workaround by generating an image map in an helper tool, but not very handy)
- Image-based lighting limited to _square_ images (I did not manage to find any square HDR on web!)
- Batch-mode by default (there is a progressive mode, but you need to pipe with tev, not very handy)
- Denoiser in a separate tool
- Last version of CUDA (11.3) not supported...

I don't blame pbrt, as it is not intended as a general public rendering tool, but as an educational support for rendering engine development. But for our needs in FreeCAD, it will not be sufficient, I think.

So I end pbrt plugin development at this point.

**Comment by claudiomush** [comment]
Hello,
I'm a bit surprise for this speed. It's amazing even with limits you saw; I prefer to see your work as a start becoming better in a future. Now how can I try this new toy?
Best regards

**Comment by claudiomush** [comment]
Hello, my first try was probably wrong because I got a sum of errors in console.
So the second attempt was using a single object. All steps flows plainly but where I can catch the result?

**Comment by howetuft** [comment]
Hello,
Could you please join your FreeCAD files (your first try, and your single object one)? I'll try to have a look...

**Comment by claudiomush** [comment]
On Tue, 25 May 2021 07:53:28 -0700
howetuft ***@***.***> wrote:

> Hello,
> Could you please join your FreeCAD files (your first try, and your
> single object one)? I'll try to have a look... 
> 

Hello, my first try was the big assembly(version 4), visible on
the picture at top of this issue too big to attach here.
But the single object is small enough.
On general properties of render I added a proper path for pbrt
executable without any other flag. Have I to force here a namefile for
result image?
Could I write a permanent file instead of temporary one just to
debugging? 
What I'm doing wrong?

**Comment by howetuft** [comment]
Hello,

Could you please attach your second file (single object)? It would be much easier for me...

For the first file, if it is too heavy to attach here, maybe you can create a repo in github and upload the file?

Thanks in advance

**Comment by claudiomush** [comment]
Hello, created a repo named models, at now private. Inside there's a little assembly, starting with as4... but as single model you could get "Pettine_lungo" as try. If the private mode is a visibility problem please tell me how to do.
Thanks

**Comment by howetuft** [comment]
Hello, it's allright, I have acces to your repo. I'll have a look this week-end.

**Comment by howetuft** [comment]
It seems that your model lacked a render project (please refer to [documentation](https://github.com/FreeCAD/FreeCAD-render#usage)).
I created one, in 'as4_dima_crimp', and I can get an output as expected:

![PbrtProjectgto5_lih](https://user-images.githubusercontent.com/34142192/120070804-91dbfd00-c08c-11eb-9b06-f5377389e1a1.png)

I committed and pushed my modifications to your repo, just tell me if it works for you.

**Comment by claudiomush** [comment]
Great!. In may attempt I'm unable to see "Model@PbrtProject" that's in you one. How to do that? My pbrt runs, if I use the pbrt file pinched up from /tmp an image was produced. So I'm wrong something in Freecad but I don't know where.
I'll try to make a movie of my steps the I''l put it in repo, in case you would tell me if correct. 
![Screenshot at 2021-05-29 19-17-29](https://user-images.githubusercontent.com/83174729/120079325-98319f80-c0b3-11eb-94e1-a0b7e191930e.png)

**Comment by claudiomush** [comment]
Hello, following your suggestion I'm able now to tender at least a simple object. There is anyway something of strange because even assigning a metal as inox I get only glass render. I attach a grab of Freecad and an sample of the pbrt file generated in tmp.
![Screenshot at 2021-05-29 20-52-22](https://user-images.githubusercontent.com/83174729/120081953-7ab70280-c0c0-11eb-83b7-be5ff46b8674.png)
![Screenshot at 2021-05-29 20-53-23](https://user-images.githubusercontent.com/83174729/120081954-7db1f300-c0c0-11eb-978e-769037108d03.png)

**Comment by howetuft** [comment]
Nice!
The problem with the material is that the Rendering section of the standard FreeCAD materials is not populated. So what you see is actually a default material. You can edit the material rendering settings with the 'Edit Material Render Settings' action in the toolbar.
I'm thinking about how to create a library of render materials.

**Comment by howetuft** [comment]
Just a side note: if you want your PointLight, AreaLight and Camera to be taken into account in your rendering, you must create a View for each of them in your Rendering Project.

**Comment by claudiomush** [comment]
Again precious suggestion; would you add them to workbench README? A library of materials would be a popular benefit so I ask myself where to catch, possibly, some sources. Coming back to define a material property: are they any specs about what freecad ask for?

**Comment by claudiomush** [comment]
> Nice!
> The problem with the material is that the Rendering section of the standard FreeCAD materials is not populated. So what you see is actually a default material. You can edit the material rendering settings with the 'Edit Material Render Settings' action in the toolbar.
> I'm thinking about how to create a library of render materials.
How about  a spreadsheet, just to try if flexible enough?

**Comment by howetuft** [comment]
Everything about materials here: https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/Materials.md and in FreeCAD documentation...

**Comment by claudiomush** [comment]
I'm unable to edit any material inside Materials. I'm a bit confused: are the visual properties under [Graphical] or under [Rendering]? It seems they aren't kept after addition and anyways the aren't visible on rendering. How to try a passthrough definition to shot inside pbrt?

**Comment by howetuft** [comment]
Hello,
To avoid long explainations, I've added some materials (and lights) to your test model in your repo, as an example. Some of them are "passthrough".
You should be able to get such a rendering:
![PbrtProjectgto5_lih](https://user-images.githubusercontent.com/34142192/120884322-d0207180-c5e2-11eb-9c4e-805eaa3b8f5c.png)
To answer your question: the rendering parameters should be under [Rendering] in the material card. But none is not populated at the moment, this should be the goal of a rendering material library, see my post before. So you have to fill it in FreeCAD and it is not persistent in the material card.

**Comment by claudiomush** [comment]
Nice picture, what I was searching for. I'll try to write something for example a table of common materials for a cut&paste  "pbrt passthrough".  
![Screenshot at 2021-06-06 15-52-39](https://user-images.githubusercontent.com/83174729/120926950-5ae69680-c6df-11eb-9e89-06cbcb470c45.png)

**Comment by claudiomush** [comment]
Only thanks to you work I'm able to build the image in attach. It isn't yet a "good" render but it is an gigantic step to. Gratefully, you have another fan (waiting for a material library).
![render](https://user-images.githubusercontent.com/83174729/121025880-eaef1380-c7a5-11eb-8e20-28d12b61c82d.png)

**Comment by howetuft** [comment]
Wow, really nice! Could not imagine pbrt was capable of such renderings.

Yes, definitely, next step will be a ready-to-use material library for rendering.

**Comment by howetuft** [comment]
Hello @claudiomush,
Would you mind sharing your above model please, for instance on your repo? It appears to be a nice use case, from my point of view, and I would like to have it in my test models...
Many thanks in advance!

**Comment by claudiomush** [comment]
Hello, I'm happy you like the model. That's a new application for H.E. physics at this time under patenting, so I'm reluctant to put it in a repo. Let me ask to my boss if possible. Making practice with lights and materials I'm going to new results as the following. Now the only running materials are by "passthrough" and I can't manage "imagelight" yet but pbrt is very powerful so it's a pleasure to play with. Thanks to you for this good binding, I hope you will commit it so other people be able to test it.

![render-21006111112](https://user-images.githubusercontent.com/83174729/121664235-900c3380-caa7-11eb-9d9a-b4a8232fcf97.png)

**Comment by howetuft** [comment]
Hello,
Thank you for your answer. If there is any license issue, please ignore my request!
To my understanding, Imagelight is limited in pbrt, as you can only use a _square_ image (I could not find a single square HDR on the web).

**Comment by claudiomush** [comment]
Hello, in this site [https://www.gitmemory.com/shadeops](https://www.gitmemory.com/shadeops) is mentioned the why pbrt uses a square map and the usage of "imgtool makeequiarea" to convert it in ...? Maybe useful for you?

**Comment by howetuft** [comment]
Hello,
Yes, good catch! I didn't know this subtle detail, thank you.

**Comment by luzpaz** [comment]
what's the status of this ticket?

**Comment by howetuft** [comment]
Well, as far as I am concerned, it can be closed.
I'm currently working on the "ready-to-use material library" mentionned above, but it is a long-term work, and I think we'll be able to open a new thread when I'm done...
