### ISSUE TITLE
Never stops rendering with LuxCoreRender, README needs a few lines of guidance.

### ISSUE THREAD

**Issue by mangelozzi** [FreeCAD/FreeCAD-render#146]
I followed the 4 step guide, using LuxCoreRender, however the rendering never stops. It just keeps going. I can't find information on where to set it to stop and return the render.

Maybe the README could be updated with some information. When one searches for answers to these problems one finds blender tutorials and outdated tutorials for FreeCAD Raytracing WB.

**Comment by luzpaz** [comment]
Please always add your full FreeCAD [About](https://wiki.freecadweb.org/About) version

**Comment by howetuft** [comment]
Well, I don't intend to substitute myself for the documentation of each renderer. But if you want to add some instructions to the doc, contributions are welcome. Some answers nevertheless:
LuxCore is by default an endless rendering engine.
If you want to stop it, you have to set up halt conditions, see [here](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.3#Rendering_halt_conditions) (e.g. via the command line).
To export rendering, the way I've found (I don't pretend it is the best) is: Tool --> Image View + Film --> Save outputs. Filename is set in Window --> Film Outputs editor

**Comment by LordDarien** [comment]
> 
> 
> Well, I don't intend to substitute myself for the documentation of each renderer. But if you want to add some instructions to the doc, contributions are welcome. Some answers nevertheless:
> LuxCore is by default an endless rendering engine.
> If you want to stop it, you have to set up halt conditions, see [here](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.3#Rendering_halt_conditions) (e.g. via the command line).
> To export rendering, the way I've found (I don't pretend it is the best) is: Tool --> Image View + Film --> Save outputs. Filename is set in Window --> Film Outputs editor

So where does LuxCore save the output render? I can't seem to find it anywhere on my PC.

FreeCAD About:
OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Philippines (en_PH)

LuxCore v2.5

**Comment by howetuft** [comment]
Well, good question! I usually find it in my user directory, but I use Linux... And I'm sorry, I'm not skilled enough in Luxcore.
Maybe you should ask Luxcore devs? Or, as an alternative, you could set a very distinctive filename (with Film --> Save outputs) and run a complete lookup on your directory tree...

**Comment by LordDarien** [comment]
> 
> 
> Well, good question! I usually find it in my user directory, but I use Linux... And I'm sorry, I'm not skilled enough in Luxcore.
> Maybe you should ask Luxcore devs? Or, as an alternative, you could set a very distinctive filename (with Film --> Save outputs) and run a complete lookup on your directory tree...

I did just as you suggested, searching for the file name. And then rendered 3 different FreeCAD files located in 3 different file folders (which I did for file organization).

1st file's Save Output showed up in the directory for the .INI file for the POV-Ray Rendering WB I had previously installed while waiting for a response to this question.

2nd file's Save Output showed up in the same file folder of the FreeCAD file.

3rd file's Save Output showed up in the same file folder as the 2nd file.

Then when I tried and uninstalled POV-Ray Renderin WB, LuxCore just closes (crashes?) when I hit Save Output, and the file doesn't show up in search.

It's like Russian Roulette! Can a dev from Rendering WB tell me show to set up the directory/file path where the rendered image goes? Because what's the point of being able to render your 3D models if you can't use them outside of the 3D modeling software?

FreeCAD About:
OS: Windows 10 Version 2004
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.24276 (Git)
Build type: Release
Branch: releases/FreeCAD-0-19
Hash: a88db11e0a908f6e38f92bfc5187b13ebe470438
Python version: 3.8.6+
Qt version: 5.15.1
Coin version: 4.0.1
OCC version: 7.5.0
Locale: English/Philippines (en_PH)

LuxCore v2.5

**Comment by howetuft** [comment]
Maybe you can try `-d `option on luxcoreui command line.

The steps to follow:

- Open Render preferences in FreeCAD (`Edit --> Preferences --> Render`)

- Edit `LuxCore UI path` parameter: in the command, add a `-d` option with the path of your target directory. Don't forget to enclose the target path into quotes, it's safer.

For instance, for me, the result looks like that: `/usr/bin/luxcoreui -d "/home/howetuft/renderings"` but please note I'm on Linux and the path points to my personal directory, so it's just to give you a general idea: you'll have to _adapt it to your system_.

Please let me know if it works.

**Comment by LordDarien** [comment]
> 
> 
> Maybe you can try `-d `option on luxcoreui command line.
> 
> The steps to follow:
> 
>     * Open Render preferences in FreeCAD (`Edit --> Preferences --> Render`)
> 
>     * Edit `LuxCore UI path` parameter: in the command, add a `-d` option with the path of your target directory. Don't forget to enclose the target path into quotes, it's safer.
> 
> 
> For instance, for me, the result looks like that: `/usr/bin/luxcoreui -d "/home/howetuft/renderings"` but please note I'm on Linux and the path points to my personal directory, so it's just to give you a general idea: you'll have to _adapt it to your system_.
> 
> Please let me know if it works (or not).

Thank you! That Actually worked! I guess I'll just have to keep a repository for the render outputs then just move them to the right project's folder.

I wish they had a more "per render" way of setting up where the render output gets saved.

**Comment by howetuft** [comment]
Fine! I close the topic...

**Comment by mangelozzi** [comment]
> Well, I don't intend to substitute myself for the documentation of each renderer. But if you want to add some instructions to the doc, contributions are welcome. Some answers nevertheless:
> LuxCore is by default an endless rendering engine.
> If you want to stop it, you have to set up halt conditions, see [here](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.3#Rendering_halt_conditions) (e.g. via the command line).
> To export rendering, the way I've found (I don't pretend it is the best) is: Tool --> Image View + Film --> Save outputs. Filename is set in Window --> Film Outputs editor

Thanks for that info. The link says:

> The file ending of the render configuration file is ".cfg", for the scene file it's ".scn".
> These files are usually created by exporter plugins, e.g. BlendLuxCore.

In this case Im guessing the export plugin is FreeCAD? Where does freecad create the configuration file so one can set a stop condition?
