### ISSUE TITLE
Where is the LuxcoreRender config file for the FreeCad Render Plugin?

### ISSUE THREAD

**Issue by mangelozzi** [FreeCAD/FreeCAD-render#147]
Unfortunately issue #146 was closed, and I can't reopen it:

> Well, I don't intend to substitute myself for the documentation of each renderer. But if you want to add some instructions to the doc, contributions are welcome. Some answers nevertheless:
> LuxCore is by default an endless rendering engine.
> If you want to stop it, you have to set up halt conditions, see [here](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.3#Rendering_halt_conditions) (e.g. via the command line).
> To export rendering, the way I've found (I don't pretend it is the best) is: Tool --> Image View + Film --> Save outputs. Filename is set in Window --> Film Outputs editor

Thanks for that info. The link says:

> The file ending of the render configuration file is ".cfg", for the scene file it's ".scn".
> These files are usually created by exporter plugins, e.g. BlendLuxCore.

In this case Im guessing the export plugin is FreeCAD? Where does freecad create the configuration file so one can set a stop condition?

**Comment by howetuft** [comment]
Hello,

You can set the stop condition, as well as other specific options, in the template file.

Let's take the 'standard' template for example: 
https://github.com/FreeCAD/FreeCAD-render/blob/master/templates/luxcore_standard.cfg
You can see that there are 2 sections: `[Configuration]` and `[Scene]`.
At runtime, these two sections will be splitted into the two files expected by LuxCore (*.cfg and *.scn).
If you want to add some custom directives, you can enrich any of those sections with the desired statements.
For instance, for a time halt condition at 10s, I guess you would add something like `batch.halttime = 10.0` in the `[Configuration]` section (but I let you explore [LuxCore documentation](https://wiki.luxcorerender.org/LuxCore_SDL_Reference_Manual_v2.5#Rendering_halt_conditions) for a more precise approach).

Two advices:

- On your system, you will find the templates files in the 'templates' subdirectory of Render WB installation folder. Look at the FreeCAD documentation to see where the external workbenches (and consequently Render WB) are installed on your system.
- Do not modify the original template file, but create a new one with your customization. Standard templates are supposed to be the same from a system to another, to ensure FCStd files portability.
