### ISSUE TITLE
Texture rendering with Luxcore

### ISSUE THREAD

**Issue by dcapeletti** [FreeCAD/FreeCAD-render#150]
Hi I am currently using Render Workbench with LuxCore to render my projects which is working fine. But now I would like to add textures, I have done it with Arch texture but I can't get them to render. 
Please I need documentation and help to render with textures. I have seen it done in this thread https://forum.freecadweb.org/viewtopic.php?f=10&t=39168&start=20#p335686 but I have no idea how to do that. 

Thanks

**Comment by howetuft** [comment]
Closing this issue: textures have been introduced in last version of Render WB (2022.03)!
