### ISSUE TITLE
Particular Assembly4 model fails to render correctly

### ISSUE THREAD

**Issue by vectronic** [FreeCAD/FreeCAD-render#151]
Hello,

(Please note: I have also asked this on the FreeCAD forum but didn't get any responses...) 

I am posting here as I believe this is a bug in the render workbench but am happy to be told otherwise...

I have previously successfully rendered an assembly4 model using the render workbench with cycles:

<img width="391" alt="Screenshot 2021-09-28 at 10 49 40" src="https://user-images.githubusercontent.com/32313864/135841663-fa7d3a1d-eea4-4928-8efc-d0833184f7ca.png">

I now have a new assembly4 model and am unable to get it to render correctly:

<img width="385" alt="Screenshot 2021-09-28 at 10 39 23" src="https://user-images.githubusercontent.com/32313864/135841704-c830e633-db3e-4fae-9828-dde6097ac238.png">

As you can see the bottom half of the model is not rendered at all, the base doesn't exist and the background is black.

I have double checked all of the render settings and model links etc. but I cannot see what is the difference between my two models which is causing this issue.

I have updated to the latest version of the Assembly4 and Render workbenches.

Does anyone have any suggestions or insight as to what could be going wrong?

Alternatively, any tips on how I could debug this myself?

I have made available the 2 assembly models here:

https://f001.backblazeb2.com/file/vectronic-public/freecad/render-working.zip (main model file: brick_assembly.FCStd)

https://f001.backblazeb2.com/file/vectronic-public/freecad/render-broken.zip (main model file: brick_assembly_2.FCStd)

Thanks very much,
Nick

**Comment by howetuft** [comment]
Hello,
I can't download the files from your links: could you please check? Thanks!

**Comment by vectronic** [comment]
Thanks for looking.

That was a copy and paste error. Try again.

**Comment by howetuft** [comment]
Hello,
First of all, I don't have Cycles on my present computer, only LuxCore, so my diagnosis is only partial at this stage (I will only be able to take a closer look in a few hours).

However, I think there is at least an issue with the GroundPlane.

In terms of position, your ground plane cuts your assembly, so the rendering seems clipped. If you shift the ground plane by -12mm (GroundPlaneZ parameter), the whole model appears. However, with LuxCore, the ground plane is black and the rendering is burnt.
![image](https://user-images.githubusercontent.com/34142192/135869662-8e047bf6-683e-419e-a84f-86d25768197c.png)
Alternatively, if I removed the ground plane, everything is ok - except there is no ground plane.
![imageNoGP](https://user-images.githubusercontent.com/34142192/135869925-81d5208f-f3b3-43ab-986d-b5aed93622e7.png)
Do you get the same results with Cycles?

**Comment by howetuft** [comment]
OK, I figured out what was wrong, 2 things actually:
1. There is an 'LCS_Origin' in the Assembly, and this component makes the generated ground plane _infinite_. You have to hide this component (right-click, 'hide selection' ; or space bar).
2. The ground plane is not well positioned in Z, according to your model. It must be placed at -12 mm (GroundPlaneZ parameter).
This being done, it should work. In any case, I get a more satisfactory result:

![brick_assembly_2](https://user-images.githubusercontent.com/34142192/135921089-9047da1d-418a-4e1b-8772-4facb6cade8b.png)

**Comment by vectronic** [comment]
@howetuft you always have the answers!

![brick_assembly_2](https://user-images.githubusercontent.com/32313864/136010563-4768f681-fef3-49f8-ba1a-935f273ed4da.png)

You found the two important differences between my two models which I failed to see.

Thanks very much.
