### ISSUE TITLE
Transparence value for Renderglass mat

### ISSUE THREAD

**Issue by claudiomush** [FreeCAD/FreeCAD-render#175]
Hello, setting transparency values lower than 100% I've no visible effects, engine cycles.
Here a value of 100%:
![Screenshot at 2022-01-31 13-31-41](https://user-images.githubusercontent.com/83174729/151795059-bf460b28-1b45-4b28-adb2-3d4053a8f91f.png)
and here the same at 10%:
![Screenshot at 2022-01-31 13-33-14](https://user-images.githubusercontent.com/83174729/151795105-3bd57ef8-a5ef-4954-b350-7570b5c8cb2f.png)
Where am I wrong?
Best regards
[assy_flange_transp_bad.zip](https://github.com/FreeCAD/FreeCAD-render/files/7970718/assy_flange_transp_bad.zip)

**Comment by howetuft** [comment]
Hello,
This is not a bug. Glass material in physical based rendering does not have any transparency parameter - see for instance https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/glass.html or https://wiki.luxcorerender.org/LuxCoreRender_Materials_Glass...
The Transparency parameter you see is just FreeCAD stuff (don't ask me what for, I'm not involved in that :wink: ), not usable/used in rendering...
All the rendering parameters taken into account are under material 'Render settings' submenu.
However, if you need something mixing a diffuse and a glass, with something like a transparency, you can modify Material Type to Mixed.

**Comment by claudiomush** [comment]
Oh, I'm very sorry, my ignorance is a trap, I see.
Many thanks.

**Comment by howetuft** [comment]
You're welcome!
