### ISSUE TITLE
Transparence value for Renderglass mat

### ISSUE THREAD

**Issue by claudiomush** [FreeCAD/FreeCAD-render#178]
Hello, sorry about reopen a closed issue.
Even defined "mixed" a "glass" material, giving 10% of transparency for that material I see no difference of rendering.
It seems transp value was ignored (cycles engine).
Where am I wrong?
[assy_flange_transp_bad.zip](https://github.com/FreeCAD/FreeCAD-render/files/8077988/assy_flange_transp_bad.zip)
![Screenshot at 2022-02-16 09-17-44](https://user-images.githubusercontent.com/83174729/154223590-ff5f975e-1f57-4181-876e-0a28199c8b60.png)

**Comment by howetuft** [comment]
Hello,
You're welcome!
Transparency is a float, not a percentage. So, if you want 10%, you must enter 0.1...
(and if I were you, I would rather try 0.8 or 0.9, like below).
![image](https://user-images.githubusercontent.com/34142192/154353918-d78ee97e-db02-450c-a2b2-266734f8452f.png)

**Comment by claudiomush** [comment]
Ops, I was wrong again.
Many thanks

**Comment by howetuft** [comment]
You're welcome!
