### ISSUE TITLE
can't use "placement" or "transform" on lights

### ISSUE THREAD

**Issue by karlp** [FreeCAD/FreeCAD-render#179]
I'm trying to place area lights and point lights, and I can use the combo view to edit the position by hand, but I can't use the edit->placement dialogs?  Is this intentional?

render workbench v: 2022.1.0

```
OS: Fedora 34 (Workstation Edition) (GNOME/gnome)
Word size of FreeCAD: 64-bit
Version: 0.20.27319 (Git) AppImage
Build type: Release
Branch: (HEAD detached at 67706b1)
Hash: 67706b14df32b91b948952ea2c9350948ba4d4db
Python version: 3.9.10
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.3
Locale: English/United States (en_US)
```

**Comment by howetuft** [comment]
Hello,
Thank you for your feedback! Not sure edit-->placement can fully apply to scripted objects (like Render lights), but I will take a closer look this weekend...

**Comment by howetuft** [comment]
Good point, indeed!
It used to work perfectly with FreeCAD last stable version 0.19 (which I use for dev...), but v0.20 has introduced a new requirement on scripted objects to be eligible to Placement feature (for those who care: they must derive from `App::GeometryPython`, and not only from `App::FeaturePython`).
I have upgraded code for AreaLight and Camera objects (6d86bdea0052be5fd9eb6aca5caeeed3b442f929), so this should be functional again. However, 2 limitations at the moment:
- This will apply only to new objects. Already created AreaLights or Cameras are definitely of the old type, and not eligible to v0.20 Placement feature. They should be recreated if needed.
- This will not apply to PointLight. However, please note this is not a regression. Indeed, PointLight does not have - and has never had -  any Placement property, as it makes no sense to apply a rotation to a PointLight (as a point...). Therefore there has never really been any support from Placement feature to PointLight, in fact.

I may look further what I can do to alleviate those two points...
Meanwhile, your feedback on the fix would be much appreciated.

**Comment by howetuft** [comment]
Update: I've also found a way for PointLight to support Placement & Transform tools, I've upgraded code accordingly (e8934e06eda0f3b5567d63145423f892f711cecc). Same limitation as Area and Camera however: it is only for new objects, existing PointLights will not benefit from that and they should be recreated if needed.

**Comment by howetuft** [comment]
I find no way to apply feature to existing objects, but it does not appear blocking to me, as they can be rebuilt if needed, so I close the issue...
