### ISSUE TITLE
Error when render button pressed.

### ISSUE THREAD

**Issue by vasto7** [FreeCAD/FreeCAD-render#180]
I get the following error message.
14:59:37  Unable to locate renderer executable. Please set the correct path in Edit -> Preferences -> Render

OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.27428 (Git)
Build type: Release
Branch: master
Hash: 27460358508a2057e0ec57a418641435f12628dd
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: English/United States (en_US)

**Comment by howetuft** [comment]
Hello,
The error message is self-explanatory: you have to fill in the path to your renderer executable in workbench settings.
Please have a look at documentation (https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/EngineInstall.md)...

**Comment by qume** [comment]
I am also having this problem. The path is set correctly. I have tried everything, including moving it to a different location, changing forward slashes to backslashes, but just get that same error message.

**Comment by howetuft** [comment]
Hello @qume,
Sorry for the inconvenience. Could you please take a snapshot of your workbench settings, to help me diagnose the problem? Thanks in advance...

**Comment by qume** [comment]
No problem. Hopefully these help. Same behaviour on 0.19 and 0.20.1

![image](https://user-images.githubusercontent.com/312180/190933164-f0391762-73b9-4fbf-8d49-d659d5c2a2a0.png)
![image](https://user-images.githubusercontent.com/312180/190933174-ceb739c9-7141-47e3-ae89-f5a0111f9768.png)

**Comment by howetuft** [comment]
Can you try to fill in the second field 'Appleseed Studio path', in settings? Possible value may be: `C:/luke/appleseed/bin/appleseed.studio.exe` (but please check carefully).

**Comment by qume** [comment]
Interesting, that worked, even though I could swear I tried that before. I think in the docs somewhere it says the appleseed studio path is optional, so I didn't play around with it much.

Much appreciated!

**Comment by howetuft** [comment]
Good news!
I admit all of this is not very clear. Appleseed command CLI is a remnant of a previous approach (where user had a choice between CLI and GUI), but is error-prone and should be removed IMHO. 
Anyway, I'm glad it works for you now. Enjoy!
