### ISSUE TITLE
Any inclination or ideas for Render WB participation in GSoC ?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#189]
Just wondering if there was any interest for Render WB to offer proposals as part of GSoC2022 ?
Mentoring a student to add features etc...

**Comment by howetuft** [comment]
Hello,
As far I am concerned, no, I don't think there would be enough material to feed a GSoC project (and, moreover, I personally wouldn't really have enough time for mentoring)...
