### ISSUE TITLE
Mitsuba 3 is now available (add as possible render engine to this workbench?)

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#199]
twitter thread: https://twitter.com/wenzeljakob/status/1549710217616711680

git repo: https://github.com/mitsuba-renderer/mitsuba3

**Comment by howetuft** [comment]
I close this issue: my personal orientation is to continue working on the already implemented renderers. There are still a lot of features to implement (spot lights, constant lights, mesh subdivision, material library, renderer specific parameters...), for the benefit of even more realistic and user-friendly renderings, and I think this is more of a priority than adding yet-another-renderer that won't provide much additional functionality compared to the others...
