### ISSUE TITLE
Procedural API

### ISSUE THREAD

**Issue by adizhol** [FreeCAD/FreeCAD-render#225]
Hello,

Is it possible to setup a scene and render it using python scripting? (Automation)
I mean, no clicking on UI involved?

Thanks

**Comment by howetuft** [comment]
Hello,

YES! A few months ago, I made special effort to have so (so I'm pleased to find a client today ;-))
This script should demonstrate the capability, just copy/past in the console:

```python
from os import path
import Render

# Adapt the 2 following lines if you want to change renderer
# Caveat: we assume that the external renderer program has been correctly
# installed and the path to that program has been correctly set in FreeCAD
# parameters

RENDERER, TEMPLATE = "Povray", "povray_standard.pov"
# RENDERER, TEMPLATE = "Luxcore", "luxcore_standard.cfg"
# RENDERER, TEMPLATE = "Cycles", "cycles_standard.xml"
# RENDERER, TEMPLATE = "Pbrt", "pbrt_standard.pbrt"


# Create a new doc
doc = App.newDocument("RenderTest")

# Create a rendering project
template_path = path.join(Render.WBDIR, "templates", TEMPLATE)
_, proj, _ = Render.Project.create(
    doc, renderer=RENDERER, template=template_path
)
proj.GroundPlane = True

# Create an object and add its view to project
box = doc.addObject("Part::Box", "Box")
box.recompute()
proj.Proxy.add_view(box)

# Create a camera, position it and add its view to project
_, cam, _ = Render.Camera.create(doc)
cam.Placement = App.Placement(
    App.Vector(40, -30, 50), App.Rotation(App.Vector(-0.7, -0.3, -0.6), 300)
)
proj.Proxy.add_view(cam)

# Render
# wait_for_completion should be set to True if freecadcmd is launched in script
# mode, otherwise freecad will exit without completing rendering.
# to the contrary, in interactive console mode, wait_for_completion may be better
# set to False (default)
img = proj.Proxy.render(wait_for_completion=True)
print(f"Done: {img}\n")

```
Can you let me know if it is OK for you?

**Comment by adizhol** [comment]
@howetuft cool! Thanks!
I will try it later.
How to I initialize "App" ?
Can I call Renderer APIs in a detached python console - not within FreeCAD?

**Comment by howetuft** [comment]
> How to I initialize "App" ?

Basically, it's already defined in FreeCAD console.
But if you want to define it explicitly:
```python
import FreeCAD as App
```

> Can I call Renderer APIs in a detached python console - not within FreeCAD?

Yes, there are 2 solutions:

1. Use `freecadcmd`, the console version of FreeCAD. It does not open a GUI, just a console. You can also pass the script as a command-line argument.
2. Import FreeCAD in a standard Python console. It's more tricky, as you must make Python aware of  FreeCAD installation. To do that, you have to add this in the header of the above script:
```python
import sys
sys.path.append("your/path/to/your/freecad/libs")
import FreeCAD as App
```
For instance, on my Arch Linux system, it resolves into
```python
import sys
sys.path.append("/usr/lib/freecad/lib")
import FreeCAD as App
```

Just out of curiosity, what is your use case precisely?

**Comment by adizhol** [comment]
cool! It's worth adding these steps to the Wiki/documentation pages.

Basically I want to render floor plan from 2d floor plans
