### ISSUE TITLE
[answer] OSS render engine for SketchUp

### ISSUE THREAD

**Issue by elrumordelaluz** [FreeCAD/FreeCAD-render#230]
As pointed in the title, this is most a question in case you that work in this cad-3d world know something to point me: is there an OSS render engine that works with Sketchup Pro?

Thanks in advance and congrats for the work you are doing in OSS and CAD.

Lionel

**Comment by howetuft** [comment]
Dear Lionel,
Unfortunately, I have no expertise in SketchUp, so I won't be able to answer you.
All I can do is encourage you to use free CAD software instead ;-)

**Comment by elrumordelaluz** [comment]
thank you!
