### ISSUE TITLE
Luxcorerender set amount of passes

### ISSUE THREAD

**Issue by redPanther** [FreeCAD/FreeCAD-render#242]
Hi,
Thx for the great work! I recently got menaged to setup render workbench with Luxcorerender on Ubuntu.
It works so far, but I have some minor inconvenience. When start render it never stops. It does endless passes. When I close the window, the rendered image is displayed in Freecad.

Is there a possibility to set amount of passes for the renderer?

**Comment by howetuft** [comment]
Hello @redPanther,

Thank you for your support!

About your question: Well, yes and no. 

- Yes: if you select Batch Mode (`Batch Mode` parameter to `True` in Luxcore Project), and you set `Samples Per Pixel` to a non-zero value, it will stop after this threshold. As a counterpart, you'll only see the final result.
- No: if you select GUI mode (`Batch Mode` to `False`), you can control the number of passes, but the window will never close by itself. Moreover, it may denoise and save endlessly... This is the way Luxcore works - or at least the best way I could have it work...

For this reason, I myself almost only use Batch Mode.
