### ISSUE TITLE
Are LinkGroups supported in renderings?

### ISSUE THREAD

**Issue by ergodicbreak** [FreeCAD/FreeCAD-render#247]
Hello, I just tried Render for the first time today so maybe I'm doing something wrong. But if I add a LinkGroup to the project, I get the error 

`15:17:23  [Render] Cannot render view 'partsGroup@PovrayProject': Unhandled object type (App::LinkGroup, App::LinkGroupPython) (file /home/george/.local/share/FreeCAD/Mod/Render/./Render/renderables.py, line 170 in get_renderables). Skipping...`

I saw someone say in the forum that Render supports LinkGroups, but maybe they were mistaken? 

Render was also recommended to render assembly3 groups but I've seen issues with that as well, https://forum.freecad.org/viewtopic.php?p=478443#p478443

**EDIT**:  I learned one workaround; I added the LinkGroup into an Arch Equipment, and that rendered. 

What are my options for rendering a grouped item? Thank you!

**Comment by howetuft** [comment]
Hello,

Thank you for trying Render and for your feedback!

About LinkGroup: no, at this time, Render does not support this feature... as I must confess I hadn't heard about it before reading your post. I'll try to have a look at it.
Could you please attach your file, so I can test on real use case?

About Assembly3: I think it should work, as Render WB is able to render the Parts section of the assembly. It may complain it cannot create views for the other components (elements...), but that should not be a problem as they are not to be rendered.
Again, if you have a test file, could you please attach it?

> What are my options for rendering a grouped item? Thank you!

I don't really know precisely what kind of use you target, so my answer may be out of scope, but another option for assemblies is Assembly4, which is supported by Render. Does it fulfill your need?

**Comment by ergodicbreak** [comment]
Thanks for the reply, I've attached a test case file. When trying to add the Link (I should note, I was calling it "LinkGroup" but I am a newbie to FC and I think the more accurate term is App::Link, https://wiki.freecad.org/Std_LinkMake#Usage), I get the error 

`09:53:37  [Render] Unable to create rendering view for object 'cubeAndCylinder': unhandled object type`

[example_linkgroup_render.zip](https://github.com/FreeCAD/FreeCAD-render/files/11151011/example_linkgroup_render.zip)

I made this Link by right-clicking on the object in the tree and selecting  Link Actions -> Make Link Group -> Simple Group

If I select this new Link and then click the Make Link icon in the toolbar, then run Render, I get a slightly different error similar to the one in this issue's first comment:

`09:57:52  [Render] Cannot render view 'cubeAndCylinder001@PovrayProject': Unhandled object type (App::LinkGroup, App::LinkGroupPython) (file /home/george/.local/share/FreeCAD/Mod/Render/./Render/renderables.py, line 170 in get_renderables). Skipping...`

Thanks for the Assembly4 suggestion, it's on my list of things to try.

**Comment by howetuft** [comment]
Thank you for the file. And, unfortunately, I confirm the LinkGroup object is not supported at the moment, so the error message makes sense - although not very pleasant.
But give me some time, I'll try to write some code for that. In the meantime, I hope you'll find contentment with the assemblies...

**Comment by howetuft** [comment]
Hello

**Comment by howetuft** [comment]
I reopen, as the issue was not solved.
I implemented the feature, actually LinkGroup is very close to Array, so it was just a small adaptation (#248 ). Could you please give it a try and confirm me it's OK for you? Thanks!

**Comment by ergodicbreak** [comment]
Very nice, it works! Thanks @howetuft.
