### ISSUE TITLE
Controlling Transparency - Cycles

### ISSUE THREAD

**Issue by the-wasters-of-time** [FreeCAD/FreeCAD-render#257]
Hi, I'm fairly new to FreeCAD, but I managed to set up Render with Cycles. I'm on Manjaro, Linux. I was using a set of files that were imported from Autodesk Inventor (as STEP files) and combined as an assembly in FreeCAD. When I render the model, the image comes out as transparent. I have the render sensitivity set to 0 for all files in the model. I did set a surface in one of the sub assembly files to be transparent (the sail membrane of the model shown in the attached image), but when viewing the full assembly in FreeCAD, the surface shows as non transparent. Is this an issue with Render, or with Cycles?

Apart from this issue, the image result looks great, but the transparency is not what I'm after :)

![ArcSail-FreeCAD-01-transparent](https://user-images.githubusercontent.com/22025513/235357492-b7b27b0c-cf46-4411-a951-2e14129d2bb5.png)

**Comment by howetuft** [comment]
Hello,
Would it be possible for you to attach the file? It would be easier for me...
By the way, I did not clearly understand the point : could you please enumerate what should be transparent and what should not?
Thanks!

**Comment by the-wasters-of-time** [comment]
Hi, Thank you for your reply. I will try to explain. The model is of an experimental sailing boat. The sail is the curved thing on top. The hulls are shown in the yellowish colour. On the rendered image, if you look at the larger hull, you can see the frames inside the outer skin of the hull. Elsewhere you can see other details which should be hidden. On the sub assembly of the sail, the sail membrane has been set to be transparent, All other parts should be non transparent. See image below of the sail assembly. I have attached the CAD files.  I'm sure I'm just doing something wrong, so thanks for taking the time to look at the issue.

![SailSubAssembly](https://user-images.githubusercontent.com/22025513/235447794-0f6bb9a2-8968-4e49-ab51-6fe56de10ff8.png)

[ArcSail-Proa-.zip](https://github.com/FreeCAD/FreeCAD-render/files/11365154/ArcSail-Proa-.zip)

**Comment by howetuft** [comment]
Hello,
Found the point, but there is still an issue... The point: all faces have got an alpha channel set to 255, so they are rendered transparent.
How to see face color:
- In the combo view, right-click on the object (for instance 'ArcSail-Proa-Hull_001') and select 'Set Colors...'
- In the viewport, click on a face of the object. The color and the face number should synchronize in the combo view (tasks)
- Click on the color. A color picker widget opens.
-  In the lower right corner, you should see the Alpha channel
If you want the face to be rendered opaque, you should set Alpha to 0. Problem: it makes the face disappear, as FreeCAD, as FreeCAD wrongly interprets alpha!
I will look again at it...

**Comment by howetuft** [comment]
A workaround may be to use material. But it works only for a whole subpart.

**Comment by howetuft** [comment]
To illustrate my last post, I've added a material for hull and rudders: here enclosed.
[ArcSail-Proa-with-material.zip](https://github.com/FreeCAD/FreeCAD-render/files/11380967/ArcSail-Proa-with-material.zip)

(NB: I worked with Appleseed, as I am travelling and I haven't got Cycles on my current PC. But it comes to the same.)

Here is the result:
![image](https://user-images.githubusercontent.com/34142192/235873540-38bd4f8a-e53e-45b8-9481-8585fb2d2866.png)

As you can see, rendering of the hull and the rudders is now opaque, fully controlled by the material (a glossy plastic).

The only limitation is that it cannot be applied to the beams of the sail, in the current situation, as the material can only be applied to a whole part (all the sail subcomponents or none of them...).
However, a solution could be to separate the beams from the rest of the sail. But I don't know if it would be acceptable for you. If this is OK, you could even separate all subcomponents of the sail and apply more accurate materials to them (for instance, metals for the skirts, and a more accurate IOR for the transparent part of the sail - current IOR is glass one).
Let me know...

**Comment by the-wasters-of-time** [comment]
Thanks for your reply, the image with the correct opacity looks great. I can do the workaround using material, I just have to learn how as I've only been using FreeCAD for a few weeks. I can separate the parts for the sail in Inventor. I also discovered that there is an Inventor import workbench, so I might have a go with that. Of course the aim is to be able to do all the modelling in FreeCAD, but It's early days for me yet.

If this is a bug, then I hope I have been of some help in bringing it toy your attention.

**Comment by the-wasters-of-time** [comment]
I did an experiment with a new part consisting of a simple primitive solid. I used the same colour as for the hull model (which I had applied to the hull model in FreeCAD) and adjusted the alpha channel value a few times. I got the expected result of varying degrees of transparency. I guess this must be an issue with the imported model.

**Comment by howetuft** [comment]
> I can do the workaround using material, I just have to learn how

You may find some information about applying a material in Render WB documentation: https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/Materials.md
Just ask me if it is unclear.

> I can separate the parts for the sail in Inventor.

I think this would be the best approach, from rendering point of view. Thus you could apply a dedicated material to each subpart.

> If this is a bug, then I hope I have been of some help in bringing it toy your attention.

I think this a bug in FreeCAD, that wrongly interprets alpha value in RGBA... 

> I'm using Cycles because it was the easiest to install on my Linux system

Cycles is a really smart engine, and if you use Manjaro, chances are you use the package I've created in the AUR ;-). But some others are worth a try: Ospray, Luxcore, Appleseed...

> I tried to install a few different renderers, Appleseed was one of them.

If you want to install Appleseed in Manjaro via AUR, you must use `appleseed-git` package, not `appleseed` one, which is broken (nota: I'm also comaintainer of `appleseed-git`).

Good luck!

**Comment by the-wasters-of-time** [comment]
Thank you very much. Your help has been amazing. I'll give Appleseed another go.

**Comment by howetuft** [comment]
Hello,
If you're happy with the answer, can you please close the issue? (and, if you're very, very happy, can you add a like to the project ;-) ?)
Thank you very much, do not hesitate to ask any other question...
