### ISSUE TITLE
<class 'AttributeError'>: 'types.SimpleNamespace' object has no attribute 'light'

### ISSUE THREAD

**Issue by thx1111** [FreeCAD/FreeCAD-render#268]
```
OS: Arch Linux (LXQt)
Word size of FreeCAD: 64-bit
Version: 0.21.0.36901 (Git)
Build type: Release
Branch: makepkg
Hash: 37f855dc130caa7c5ec33eb315e0b0c664ede8d9
Python 3.11.3, Qt 5.15.9, Coin 4.0.1, Vtk 9.2.6, OCC 7.6.3
Locale: English/United States (en_US)
Installed mods:
  * QuickMeasure 2022.10.28
  * fasteners 0.4.56
  * Assembly3 0.12.0
  * Pyramids-and-Polyhedrons
  * ExplodedAssembly
  * symbols_library
  * Render 2023.2.5
  * boltsfc 2022.11.5
  * pcb
  * kicadStepUpMod 10.19.4
  * Help 1.0.3
  * Assembly4 0.50.2
```

There is an Area Light in my tree from trying the Render module.  But now, it cannot be removed, after saving, then opening the document.  Deleting the Area Light works just after creating it, but not after re-opening the project file.  This is while running with the LinkMerge branch of freecad-linkstage3, but I don't see how that would make any difference running `Render/base.py`.

There are various "object has no attribute" errors, as for instance:

```
Traceback (most recent call last):
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 440, in onDelete
    res &= callback(feature, subelements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 815, in on_delete_mixin_cb
    self.coin.light.remove_from_scene(scene)
    ^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'types.SimpleNamespace' object has no attribute 'light'
```
and
```
Traceback (most recent call last):
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 440, in onDelete
    res &= callback(feature, subelements)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 812, in on_delete_mixin_cb
    res = super().on_delete_mixin_cb(feature, subelements)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 741, in on_delete_mixin_cb
    scene = Gui.ActiveDocument.ActiveView.getSceneGraph()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'Gui.MDIView' object has no attribute 'getSceneGraph'
```

**Comment by howetuft** [comment]
Very strange. Would it be possible for you to attach your FreeCAD please?

**Comment by thx1111** [comment]
I had to zip the zip file into a zip archive because github will not accept a regular FCStd file:
[zip.zip](https://github.com/FreeCAD/FreeCAD-render/files/11523831/zip.zip)

I thought this might be interesting - I copied and loaded the file, and then went through and deleted everything possible, which left exactly only these two Area Lights that I cannot delete.

Maybe try starting with that, to see if you can make any sense of the problem.

**Comment by thx1111** [comment]
Hmm - ok, that is not going to help.  I just tried re-opening the file I saved after deleting everything else, and then I was able to delete these two Area Lights.  So, there must be some interaction with the other components in the complete file.  Also, when I start freecad, I see these two messages, which I do not understand:
```
00:42:11  A3 available
00:42:11  Path WB not found
```
Maybe the LinkMerge branch is part of the issue?  The freecad loaded document tree must be including some kind of state, 1) when the Area Lights are first written, before the document is saved - the Area Lights can be deleted; 2) after the document has been saved with the Area Lights and then re-loaded and deleting everything - the Area Lights cannot be deleted; 3) after saving the decimated document and reloading - the Area Lights can be deleted.  Maybe this has something to do with the way the LinkMerge branch is saving the document?  Still seems odd that it would affect python.

So, try with the complete file:
[converterzip.zip](https://github.com/FreeCAD/FreeCAD-render/files/11523847/converterzip.zip)

**Comment by howetuft** [comment]
OK, I know what's going on. The bug occurs when you want to delete the Area Light but the active view is not on the 3D viewport, for instance it is on a page. Here is how to do it:
- select the viewport (click on `converterAssemblyCombined` tab)
- select `AreaLight` in the tree
- select a page _in the tabs_ (for instance `page Triangle Flange Blank`)
Now, if you press `del`, you should get the error message.
The explanation is that when you are on a page, the scene graph of the document is no longer accessible. However Render needs to access it to remove some objects attached to the Area Light.
So, a first workaround: select the 3D viewport if you want to delete a Render object. And I'll try to find a complete fix for that later.

**Comment by thx1111** [comment]
Thanks, but - yes, I *do* have the 3D viewport selected, with the `converterAssemblyCombined` tab open, and *still* no joy.  I get the same error messages.  Hmm - that raises the question about how this is working differently in your version of freecad.  I also tried selecting different active Workbenches, especially the Render workbench, but no difference.

By the way, the assemblies in the file were created with Assembly3, if that could matter.

So, does this imply that the scene graph of the document is *still* not accessible when I have my 3D viewport tab active?  Is there some direct method to indicate the status of the scene graph, some "scene graph active" indicator?  What else might affect scene graph accessibility?

**Comment by thx1111** [comment]
I'm reading at https://wiki.freecad.org/Scenegraph/en and https://wiki.freecad.org/Pivy , and I tried running this code from that page with the 3D view tab open, using Arch Linux python-pivy 0.6.8-2, and I have the "Area Light001" selected:
```
>>> from pivy import coin
>>> sg = FreeCADGui.ActiveDocument.ActiveView.getSceneGraph()
>>> print(sg)
<pivy.coin.SoSeparator; proxy of <Swig Object of type 'SoSeparator *' at 0x7f95a4fb4930> >
>>> for node in sg.getChildren():
...     print(node)
... <return>

<pivy.coin.SoPointLight; proxy of <Swig Object of type 'SoPointLight *' at 0x7f95a4fb5230> >
<pivy.coin.SoEventCallback; proxy of <Swig Object of type 'SoEventCallback *' at 0x7f95a4fb5440> >
<pivy.coin.SoSeparator; proxy of <Swig Object of type 'SoSeparator *' at 0x7f95a4fb5050> >
...
```
All else I get is a long list exactly the same in form as `<pivy.coin.SoSeparator; proxy of <Swig Object of type 'SoSeparator *' at 0x7f95a4fb5050> >` with different addresses.

Is that suppose to say "SoPointLight" for an Area Light?

When I run the code again *without* the Area Light selected, I get pretty much the same thing, beginning with `<pivy.coin.SoPointLight; proxy of <Swig Object of type 'SoPointLight *' at 0x7f95a4fb5620> >`.  Shouldn't there be some actual objects from the scene graph showing in that list?

**Comment by howetuft** [comment]
The explanation:
When Render creates an AreaLight, it also adds a SoPointLight in the scene graph, just to materialize the light in the viewport. The SoPointLight is only for display in FreeCAD, for practical reasons (it is not necessary for renderers). That is what you see in the scene graph.
So, when the user wants to delete an Area Light, Render has to delete also this SoPointLight. For that, it needs to access to the scene graph and that's where the problem lies, in your use case, as it cannot find the sg...

**Comment by howetuft** [comment]
Hello,
I made an attempt to fix: could you please retry and give me some feedback? I've directly pushed the patch to master branch, so you just have to update the workbench via the addon manager (and perhaps close and reopen your test document). Thanks in advance.

**Comment by thx1111** [comment]
Thanks.  Sorry - no joy.  By the way, when the file first loads, before even attempting to delete the Area Lights, the error messages begin with:
```
Traceback (most recent call last):
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 408, in attach
    self.on_attach_mixin_cb(vobj)  # Can be overridden by mixins
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/.local/share/FreeCAD/Mod/Render/./Render/base.py", line 807, in on_attach_mixin_cb
    scene = Gui.ActiveDocument.ActiveView.getSceneGraph()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'Gui.MDIView' object has no attribute 'getSceneGraph'
```
I'm wondering, when running the code from the website, after `FreeCADGui.ActiveDocument.ActiveView.getSceneGraph()` and then `sg.getChildren()`, how is  `Swig Object of type 'SoPointLight *'` at the top of that list?  Is that the general "lighting" for the view?  Does it have anything to do with the "Area Lights"?  This problem has to be related to the structure of the document file itself, and then, the way that it gets parsed, yes?

**Comment by howetuft** [comment]
Perhaps we are making progress, despite appearances, because this is not the same error as before! This is a call to the same `getSceneGraph`, but in a different part of my code. I'll try to fix this one too (and any others that might exist, by the way).

> how is Swig Object of type 'SoPointLight *' at the top of that list?

It is deliberately placed there, on the top of the scene graph, because a SoPointLight lights only objects that are behind them in the sg. So, if you want it to light the entire scene, you have to put it on top.

> This problem has to be related to the structure of the document file itself, and then, the way that it gets parsed, yes?

I don't think so. The scene graph is not persistent, it's recreated when the document is opened.

**Comment by howetuft** [comment]
OK, I've pushed a new fix. If you could update and test once again, it would be nice. Thanks!

**Comment by thx1111** [comment]
Ha!  Score!  Totally works - no error messages - Area Lights can be deleted!  Great work!  Many thanks!

**Comment by howetuft** [comment]
Excellent! I close, thank you and do not hesitate if you've got other questions.
