### ISSUE TITLE
Cannot add view of Assembly4 Model

### ISSUE THREAD

**Issue by sslupsky** [FreeCAD/FreeCAD-render#27]
If I attempt to add a view with a model selected from the Assembly4 workbench, it does not add the view to the render project.  In my case, I was attempting to add the view to a Povray project.  If a select a body from within one of the models, I can add that to the view.

OS: macOS Mojave (10.14)
Word size of OS: 64-bit
Word size of FreeCAD: 64-bit
Version: 0.19.19323 (Git)
Build type: Release
Branch: master
Hash: 1b198453b8eb6aa2eaca4e4be4b49fee74e9de6e
Python version: 3.8.1
Qt version: 5.12.5
Coin version: 4.0.0
OCC version: 7.4.0
Locale: English/Canada (en_CA)

**Comment by luzpaz** [comment]
You should let the Assembly4 dev know this. Please find the Assembly4 thread on the forum and post to it (link back to this ticket). Thanks

**Comment by sslupsky** [comment]
Will do that.

**Comment by sslupsky** [comment]
Here is a link to the forum post:

https://forum.freecadweb.org/viewtopic.php?f=20&t=34806&start=390#p367550

**Comment by everlanes** [comment]
Hi,

I probably stumbled accross the same problem. When trying to add a View of an Assembly 4 model, an assertion error is thrown:
  "Unable to create View: Project and Object not in same document"
It is in Render.py line 764.

I tried to remove the assertion. But then another error is thrown:
    File ".../Render.py", line 768, in create
    fpo.Source = fcd_obj
    PropertyLink does not support external object

I haven't had a closer look to understand, what should happen here. But obiously parts of the Assembly 4 model are linked to different files, aka not in the same dokument. Maybe it would be possible to add "Part.Links" in these cases?

Cheers, Andreas

**Comment by howetuft** [comment]
Hello Andreas,
If I were teasing you, I would say: thank you for confirming that the assertion did duly protect the program against unsupported input. ;-)
More seriously: yes, we now need to support Assembly4 objects. However, I don't know this workbench and I don't have a lot of time at the moment, so if you have suggestions or want to code, you are welcome.
Moreover, if you can post your Assembly4 FreeCAD model, it would be much helpful...
Thanks in advance

**Comment by everlanes** [comment]
I came one step further, but there is still something missing:

By changing ```"App::PropertyLink"``` into ```"App::PropertyXLink"``` in [Render.py](https://github.com/FreeCAD/FreeCAD-render/blob/3d3972b0b41c6e91d41125c7b08ad633ce659c19/Render.py#L677) I got rid of the mentioned error.
Now the rendering starts successfully.

But, sadly, this seems not to be enough. I suspect, that all elements are rendered now, but they are all placed at the origin. As it is just one big blob I can't tell for sure. I reckon, somehow the coordinate transformations are not applied (correctly? at all?).

I tried to add the App::Part class to list of know types, but it didn't help. Maybe I missed something.

**Comment by howetuft** [comment]
There may be a dedicated treatment to add in function 'get_renderables' in file 'renderables.py'.
'get_renderable' is the key function to convert a FreeCAD object into something renderable by an external renderer. Support for specific complex objects (like Assembly4) should be added there... Especially, specific placement rules can be implemented there.

**Comment by howetuft** [comment]
@everlanes 
Hello,
I've created a dedicated branch for Assembly4 development (the branch is named 'assembly4'). Do not hesitate to push your current state there, even as WIP, so we can look together to the issues you encounter.

**Comment by howetuft** [comment]
Hello all (@everlanes @sslupsky...)
I made an attempt to deal with Assembly4 in Render - and, by the way, improve Part support. It is directly in Master branch: if you're still here and full of enthusiasm, may you please be so kind to give me your feedback about it? Many thanks in advance...

**Comment by everlanes** [comment]
Hello @howetuft 

I just gave the current master branch a try and it is working for me. Awesome!

I have a highly nested model made of many Assembly 4 subassemblies and at a first glance they are exported and rendered correctly. It seems that for me this issue is solved.

Now I have to learn how to produce good looking renderings, with materials and so on.

Thanks,

  Andreas

**Comment by howetuft** [comment]
Hello @everlanes,
Glad to hear that! If you encounter any trouble with your next steps (materials etc.), your questions are welcome.

By the way, do not hesitate to post some screenshots of your renderings (in FreeCAD forum) if you think they are worth seeing! I am always very interested in what can be done with Render WB... 

Good luck with your models...
