### ISSUE TITLE
Text doesn't loop.

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-render#271]
I see in some windows the text doesn't loop back!
Tested in 0.21, with extreme pro dark theme.
![FreeCAD_rQ8cT8e3Ox](https://github.com/FreeCAD/FreeCAD-render/assets/29804962/26ddae72-f2c3-48e7-9746-eaabe97aa928)

**Comment by howetuft** [comment]
Hello,
Good catch, I'll see that this week-end. By the way, thank you for your supportive posts on the forum (splashscreen contest)!

**Comment by howetuft** [comment]
Hello,
I attempted a fix (#272). It is pushed to master, so you just have to update (with Addon manager): could you give it a try?

**Comment by MisterMakerNL** [comment]
Tested it on 0.21 works great!
Although I was going true my theme's and saw a pulldown menu has a fixed black background:
![afbeelding](https://github.com/FreeCAD/FreeCAD-render/assets/29804962/e2099381-6864-44c8-bfe1-d53edaf623ef)

**Comment by howetuft** [comment]
Hello,
Not sure I can do something for that, as I'm not proprietary of this field (I inherit the form from FreeCAD resources...). Will look if there is something possible anyway.

**Comment by MisterMakerNL** [comment]
That last one was totally my fault, and I fixed it which was nice to get such bugs out of my stylesheets.
I hadn't set the correct background in QComboBox:editable
Although I am not sure why the Qcombox is editable since "father" is probably a pick a name type of thing?
Anyway I am closing this!
