### ISSUE TITLE
Make it easier to install or download render engine.

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-render#273]
After sparking up discussion I noticed that most users strucle with getting a render engine.
We should probably give some direct download links for windows and Linux and Mac.
I have a direct download for cycles on Windows: https://github.com/MisterMakerNL/Cycles-stand-alone-windows-build
If we manage to get one for linux and mac then more users will definitely start using this workbench!

**Comment by howetuft** [comment]
Hello,
You're righet, this is a recurring remark...
In my opinion, it's more about Cycles, as other renderers ship binaries for every platform. For Cycles Standalone in Linux, there may be a way to use a flatpack or something like that, but I'm not very familiar with that... I must investigate.
I was also thinking of adding a feature that could "automagically" find the renderer once installed and avoid to set the renderer path in the parameters (something like `which` in Unix), for a regular installation. This would simplify the settings step.
I must think about it (and I'm temporarily involved in another project) so it may take a couple of weeks, but I'll get back to you.

**Comment by luzpaz** [comment]
> I was also thinking of adding a feature that could "automagically" find the renderer once installed

The folks at CfdOf have done a great job with this for their FEM 3rd party dependencies. See https://github.com/jaheyns/CfdOF#dependency-installation (cc @jaheyns)

**Comment by MisterMakerNL** [comment]
Did you ever seen this project:
https://bitbucket.org/gremigi/qt-cycles/src/master/

**Comment by howetuft** [comment]
Following our exchanges and the complimentary doc I wrote, I close this topic. If you have precise points about installation, feel free to open (more focused) tickets!
