### ISSUE TITLE
Rendering Assembly3 assembly don't render with constraints

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD-render#277]
When I try to render an Assembly3 assembly, it renders without the constraints applied.

Example correct assembly in FreeCad:
<img width="583" alt="Screenshot 2023-07-24 at 18 24 49" src="https://github.com/FreeCAD/FreeCAD-render/assets/2439728/89600ddc-82c5-4cf6-bd40-22c95f87df03">

When rendering the internal part is not in it's correct position:
<img width="685" alt="Screenshot 2023-07-24 at 18 26 07" src="https://github.com/FreeCAD/FreeCAD-render/assets/2439728/b8a1f58f-c9f3-444f-8b93-239adcfefbd5">

How to reproduce:
1. Create an Assembly3 assembly with constraints
2. Create the LuxCore render project
3. Select assembly and click `Rendering view` to add assembly to render
4. Render the project

I believe it's the same issue as shown here: https://github.com/realthunder/FreeCAD_assembly3/issues/1246 where rendering has no constraints applied.

**Comment by howetuft** [comment]
Hello,
Yes, you're right there is a problem. Unfortunately I'm AFK (holidays), therefore it may take a few weeks to get a fix, I apologize, but I'll take care of it when I'm back.

**Comment by howetuft** [comment]
Hello @Anthony-Gaudino,
Back to my computer, I'm going to work on this issue. Could you please attach the example file you used above? Many thanks in advance...

**Comment by Anthony-Gaudino** [comment]
Hi @howetuft

Sorry, unfortunately when trying to render, LuxCore is crashing for some reason.

I have created a minimal example that should have the issue I described.
[minimal_render_test.zip](https://github.com/FreeCAD/FreeCAD-render/files/12440334/minimal_render_test.zip)

It consists of an assembly3 assembly with a cylinder and a box on top of it.
When rendering the box should appear on top of the cylinder as in the assembly, but according to the issue I described the elements will be rendered in their original position, so the box will be touching the XY plane.

**Comment by howetuft** [comment]
Hello @Anthony-Gaudino,
Thank you for your feedback. I'm trying to tackle the point of issue, I'll come back to you soon!

**Comment by howetuft** [comment]
Hello,
As previously announced, I've written some code to handle Assembly3: #305. Could you give me some feedback? Thanks!
I'll close this issue in a few days.

**Comment by Anthony-Gaudino** [comment]
Hi @howetuft,

I was not able to fix the LuxCore crash here, so I couldn't test your changes.

**Comment by howetuft** [comment]
No problem. If you ever get LuxCore back on track, or another renderer (Povray is the most robust, for instance), do not hesitate to come back here. Meanwhile, I close the issue.
