### ISSUE TITLE
Render Workbench mesher destroys edges

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#278]
See image at
https://forum.freecad.org/viewtopic.php?p=696699#p696699
Inner edge of the upper Part is “_**rounded**_” by the mesher of the Render workbench.
The image is unusable.
Rendered with povray.

**Comment by howetuft** [comment]
Hello,
This is Autosmooth consequence. You can either deactivate Autosmooth or tweak its threshold angle.
Smoothing parameters can be accessed in the View object of your part: https://github.com/FreeCAD/FreeCAD-render/blob/master/docs/Views.md#smooth-options

Let me know if it is ok
