### ISSUE TITLE
Applying a material changes the appearance Shape color

### ISSUE THREAD

**Issue by Anthony-Gaudino** [FreeCAD/FreeCAD-render#279]
I don't know if this was made intentionally to make it visible to the user that he applied a material, but I think it should not happen.

When a Render material is applied to a PartDesign object it changes the object's appearance Shape color property.

If I set the material to be brass for example it sets the appearance Shape color to `#f5e3ad`, but the FreeCAD brass appearance shape color is `#c7901c`.

Changing the value of `Base color` on `Render settings` also changes the Shape color property, but oddly it doesn't change to the new color, but to the default color, so if one changes the brass Render `Base color` to blue color it applies the `#f5e3ad` color.

I think the Render workbench should not change the object appearance in FreeCAD.
Another option is that the Render workbench could also offer the same appearance settings as FreeCAD, so the user could set both the Render material settings and the FreeCAD Appearance settings. The advantage of this is that the user could just add the Render material and automatically also change the settings in FreeCAD. Also the user could create Material cards with those settings and import them, so he could create different reusable FreeCAD appearance settings.

**Comment by howetuft** [comment]
Hello,
It is not Render that should be blamed for that, but FreeCAD.
Indeed Render material is just an enhanced Arch Material, and the behaviour
you describe is merely inherited from Arch.
The code is here:
https://github.com/FreeCAD/FreeCAD/blob/9dce2525f8efe0873787f4388f10e11e168fe16b/src/Mod/Arch/ArchMaterial.py#L410

However, I understand your claim, so maybe we could break compatibility if
user asks so (with a checkbox in parameters) ?

Le mer. 2 août 2023, 13:12, Anthony Gaudino ***@***.***> a
écrit :

**Comment by Anthony-Gaudino** [comment]
Yes, I believe a checkbox in parameters would work.

I was wondering though if it's possible to set the Appearance settings in the Material card to allow reusability.
Do you know if this is possible in FreeCAD?

**Comment by howetuft** [comment]
I don't know if it answers your question, but as you can see in the code, the object's Shape color is set to the DiffuseColor of the material card, so you may use this field of the card for your purpose?

**Comment by howetuft** [comment]
Hello,

> Yes, I believe a checkbox in parameters would work.

The checkbox is created (#300), it is located in workbench settings (Edit --> Preferences --> Render, in the 'Advance & Debug' section'.
