### ISSUE TITLE
It should be possible to change povray-template

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#280]
As far as I can see, there is no way to change the template of a povray-project.

**Comment by howetuft** [comment]
Hello,
Yes you should be able: right-click on the Project and, in the context menu, there should be a `Change template` item. Can you let me know?

**Comment by berberic2** [comment]
O.K. this works.
But why can’t I simple change it in properties?

![Screenshot_20230805_175813](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/0e9294ee-bbc5-46a9-b182-6e6948dd2b2d)

**Comment by howetuft** [comment]
Because with the FreeCAD widget:
- there is no possibility to filter (*.pov), nor to specify target directory.
- it saves the local path, so you cannot share the freecad file after that
So I developed a special command, in a context menu.

**Comment by berberic2** [comment]
Sure?
In the Tech Draw workbench it seems to work…
![Screenshot_20230805_182713](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/50477bd3-be0f-4b4f-b892-75805701e320)

**Comment by howetuft** [comment]
Yes, but it saves the local path...

Le sam. 5 août 2023, 09:28, M G Berberich ***@***.***> a
écrit :
