### ISSUE TITLE
no save-image 

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#281]
As the image gets overwritten if rendering is started again (with different parameter, colors, …) it should be possible to save the image in the freecad-viewer.
This would make the “Copy filename to clipboard” option obsolete, which is awkward to use anyway.

This holds for the povray renderer.

**Comment by howetuft** [comment]
Ok, I plan to add a "Save as..." menu option in the context menu.
For the "Copy filename to clipboard", I will keep it anyway, as it is convenient in a few situations (upload file to web sites, open file from command line...).

**Comment by howetuft** [comment]
Hello,
I've added a "Save As..." feature in result image viewer (context menu): #293 
Can you please confirm it's ok?

**Comment by MisterMakerNL** [comment]
![render export test](https://github.com/FreeCAD/FreeCAD-render/assets/29804962/43a6399b-3489-4ef7-97bc-ca3896d0739a)
worked fine with latest cycles build.

**Comment by berberic2** [comment]
> Hello, I've added a "Save As..." feature in result image viewer (context menu): #293 Can you please confirm it's ok?

Seems to work
