### ISSUE TITLE
cycles renderer uses gamma = 1

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#282]
The cycles renderer uses gamma = 1 instead of gamma = 2.2

**Comment by howetuft** [comment]
Well, I'm surprised: Cycles Standalone should export with gamma = 2.2,  thanks to this commit:
https://github.com/blender/cycles/commit/2db39bdc99ef371a5ce66eb6d7ec733ec5fe03fc
What is your basis for your assertion?

**Comment by berberic2** [comment]
> What is your basis for your assertion?

I can see it.
![Unbenannt](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/814f7e1b-66de-45ff-993b-eab7f2eaac2a)
Left cycles, right povray

cycles version is 4.0.0, compiled from git and links against libOpenColorIO.
```
> ldd /opt/cycles/cycles | grep OpenColor
        libOpenColorIO.so.2.1 => /lib/x86_64-linux-gnu/libOpenColorIO.so.2.1 (0x00007f9986200000)
```

**Comment by howetuft** [comment]
Ok. But I'm pretty sure about gamma in Cycles output, it's 2.2. As you can see, I was the author of the update in Cycles, and, at that time, I had made some comparisons with some other engines (especially LuxCore).
Just to be sureagain: have you any possibility to compare with other renderers (LuxCore, Appleseed, ospray)?

Actually, I suspect something wrong in our understanding of povray `assumed_gamma`, especially after having read this topic:
https://www.povray.org/documentation/view/3.7.0/260/ ==> `assume_gamma` is not a standalone parameter, but is used in combination with another `Display_Gamma`.
Two things at least make me wonder in the doc:
- "no assumed_gamma in scene :No gamma correction is applied to output file." Would mean that, in Raytracing, there was no correction applied, meaning Gamma=1 ==> in other words there was a bug in Raytracing.
- "For new scenes, you should use an assumed gamma value of 1.0 as this models how light appears in the real world more realistically." Would mean previous settings in Render pov templates were right and we have to revert my recent commits.

Unfortunately, I'm away from my computer for a few days, but if you can do the comparisons, please, it would help finding the right settings. Thanks!

**Comment by berberic2** [comment]
Yes, I saw the patch was from you.

The `ImageBufAlgo::pow(image_buffer, image_buffer, {g, g, g, 1.0f});` line actually converts the image from gamma = 2.2 (?)  to gamma = 1 (it _increases_ “brightness”)
Commenting it out, makes the image look right on a gamma = 2.2 display.

**Comment by howetuft** [comment]
I'm sorry you're wrong. The code line converts image from gamma=1, no correction, which is the way a PBR rendering engine internally works (as the physical equations do not deal with gamma conversion)  to gamma=2.2.

Moreove, the code I used is directly copied from Opencolorio documentation, section `ImageBuf OIIO::ImageBufAlgo::pow`, https://openimageio.readthedocs.io/en/latest/imagebufalgo.html#_CPPv4N4OIIO12ImageBufAlgo3powER8ImageBufRK8ImageBuf5cspanIfE3ROIi
(have a look at the example...).


The direct output from renderer is not corrected (typically CIE XYZ or raw RGB) so you have to apply gamma (aka pow(1/gamma)) to convert to sRGB.
If you remove the codeline, you've got gamma=1, no correction. So when you open it in a viewer, it will assume gamma=2.2 and display wrong colors. 

Please compare also to other renderers, if you've got a doubt.

**Comment by howetuft** [comment]
I'm sorry you're wrong. The code line converts image from gamma=1, no correction, which is the way a PBR rendering engine internally works (as the physical equations do not deal with gamma conversion)  to gamma=2.2.

Moreove, the code I used is directly copied from Opencolorio documentation, section `ImageBuf OIIO::ImageBufAlgo::pow`, https://openimageio.readthedocs.io/en/latest/imagebufalgo.html#_CPPv4N4OIIO12ImageBufAlgo3powER8ImageBufRK8ImageBuf5cspanIfE3ROIi
(have a look at the example...).


The direct output from renderer is not corrected (typically CIE XYZ or raw RGB) so you have to apply gamma (aka pow(1/gamma)) to convert to sRGB.
If you remove the codeline, you've got gamma=1, no correction. So when you open it in a viewer, it will assume gamma=2.2 and display wrong colors. 

Please compare also to other renderers, if you've got a doubt.

Addendum:
Gamma encoding is pow(1/*gamma_display*), to be precise. In most cases 2.2, and 1.8 for Mac...

**Comment by howetuft** [comment]
> BTW: The cycles sunlight template. looks a bit strange.

In what way?

**Comment by howetuft** [comment]
By the way, for your information, I've reverted povray to previous `assumed_gamma 1.0`. Reading the doc (see above), I'm now convinced that Raytracing was buggy, lacking assumed_gamma definition and thus exporting with no gamma correction.
I'm conscious it may break your own perception, but the doc clearly states:
 "no assumed_gamma in scene :No gamma correction is applied to output file."
"Scenes that do not have an assumed_gamma global setting will not have any gamma correction performed on them, for compatibility reasons."
And "For new scenes, you should use an assumed gamma value of 1.0 as this models how light appears in the real world more realistically", so I'll stick to that.

**Comment by berberic2** [comment]
> In what way?

![Unbenannt2](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/b4b59c40-6c74-4439-8e2f-d316e895e93f)

**Comment by howetuft** [comment]
Ah yes, there may be an issue. Due to some obscure parameters evolution in Cycles xml import, the current code will result in selecting "Nishita improved" instead of "Hosek Wilkie" as sun type, unlike what is expected. Nishita is a very harsh model, with powerful lighting, and that's why you get this nearly burnt rendering (you can compare both models in Blender, for instance).
I've modified the code in order to enforce Hosek Wilkie selection, but I cannot test. Could you give me some feedback?

**Comment by berberic2** [comment]
I still think gamma is wrong.
![Screenshot](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/8fdc6645-573f-4155-8b3a-0825eaa8faea)
Left: FreeCAD Display. The color of the nutstone is set to nearly black (#444444) (appearance: _plausible_)
Middle: What you think is correct gamma (appearance: _**not** plausible_)
Right: What I think is correct gamma (appearance: _plausible_)

In the right image, for me, the background is too dark for `studio light`, but that’s probably because you tried to compensate for wrong gamma by setting it too dark.

**Comment by howetuft** [comment]
OK, I've understood the issue. It is not related to output but to input.
Indeed, it seems that colours in FreeCAD are gamma-corrected (sRGB colorspace), whereas input colors for renderers are expected to be in linear RGB. As I do not apply correction in input, it yields inconsistent results. 

I've made a small Blender example to illustrate. I deliberately chose Blender, just to avoid any topic about gamma-correction in output - as I leave the standard settings for this part.
In my example, I apply your color to an object with and without gamma correction (nota bene: without modifying lighting, for greater simplicity). 

Starting from your case, if I convert 0x44 to RGB, it gives R=G=B=0.267.
If I apply Gamma=1 to input, we get the following output, the same as you blamed above:
![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/cfbed396-6953-4cf4-a0c9-ebd15bb8724a)

If I now apply Gamma=2.2, we retrieve your expected output:
![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/a8deb4db-1198-4ac1-8d1d-02f8d11ad7ac)

So, my conclusion is that I assumed bad colorspace from FreeCAD inputs (linear instead of sRGB) and I must gamma-correct input colors: agree?

[TestGamma.blend.zip](https://github.com/FreeCAD/FreeCAD-render/files/12370086/TestGamma.blend.zip)

**Comment by berberic2** [comment]
> OK, I've understood the issue. It is not related to output but to input. 

> So, my conclusion is that I assumed bad colorspace from FreeCAD inputs (linear instead of sRGB) and I must gamma-correct input colors: agree?

That sounds plausible.

**Comment by howetuft** [comment]
Hello,
I have implemented the gamma workflow above:
FCD colors (srgb) => Input colors (linear rgb) => Raytracing computation (linear rgb) => Output colors to file (srgb)

To me, it seems ok, at least for Povray, Cycles, Appleseed and Pbrt (I must still investigate small differences Lux and Ospray):
![gamma](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/bd0d25aa-48b9-4636-9ecd-526a217aa9f4)

![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/3c2cc91f-51ca-4136-aeb5-c6b86cf8bd52)
(Povray)

![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/681a2f68-c1de-4512-9172-e471dd4c5c5e)
(Cycles)

![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/18a9342d-9708-4dfa-81b6-ca0ed6a0d7b9)
(Appleseed)

![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/3f422733-79b5-4f9e-860c-71c1bda4ee6d)
(Pbrt)

--> Could please confirm it is ok on your side, at least for some of these renderers? Many thanks in advance...

**Comment by howetuft** [comment]
Done for Luxcore also:
![image](https://github.com/FreeCAD/FreeCAD-render/assets/34142192/9ea1f7bf-347a-4413-9ef5-8a5d2c8157ae)

**Comment by berberic2** [comment]
Yes. looks O.K. for me.
(I only can test povray and cycles)

**Comment by howetuft** [comment]
OK, thank you. There is still a flaw in LuxCore, actually, it's too dark... But happy that pov & cycles look good.
