### ISSUE TITLE
Cycles renderer - skip_meshing and lights

### ISSUE THREAD

**Issue by Francisco-Rosa** [FreeCAD/FreeCAD-render#286]
Cycles renderer

It does not accept "skip_meshing=True".
Does not accept more than one PointLght and does not accept AreaLight.
(https://forum.freecad.org/viewtopic.php?p=693403#p693403)
[Test_animation_render.zip](https://github.com/FreeCAD/FreeCAD-render/files/12328247/Test_animation_render.zip)

**Comment by howetuft** [comment]
Hello,
Skip meshing issue should be fixed (#298).

**Comment by howetuft** [comment]
Hello,

> Does not accept more than one PointLght and does not accept AreaLight.

This was a very subtle issue to fix!
Actually, it is a consequence of the "light tree" new feature that was introduced recently in Cycles (https://wiki.blender.org/wiki/Reference/Release_Notes/3.5/Cycles). As they introduced it, they silently changed some parts of the xml syntax for the lights - and if this syntax is not observed, the light is not taken into account.
However, the new syntax is only required if we do use a light tree. And there are 2 cases when a light tree will not be used:
1. When the feature is explicitly disabled (there is a xml parameter for that).
2. ...or when there is only one light in the scene!  --> you see the bug!

I could have modified the code in the plugin to conform to the new syntax but I'd be afraid that this would create a compatibility problem for users using older versions of Cycles. Thus for now I've just disabled the feature: #299 
I may introduce later an option to let the user activate the feature.

At any rate, can you please confirm the fix works for you?

**Comment by luzpaz** [comment]
title of ticket has typo: `skip_mehing` :arrow_right: `skip_meshing`

**Comment by Francisco-Rosa** [comment]
It's working, both the "skip_meshing" and the use of more than one point of light. 
We can fully use cycles for animations . That is great!
Thanks.
