### ISSUE TITLE
Doc: detail renderer installations for Ubuntu and Windows

### ISSUE THREAD

**Issue by howetuft** [FreeCAD/FreeCAD-render#288]
For Ubuntu:
Luxcore
Povray (repo)

**Comment by howetuft** [comment]
PR #290

**Comment by MisterMakerNL** [comment]
You can get cycles stand-alone for windiws from my github https://github.com/MisterMakerNL/Cycles-stand-alone-windows-build

**Comment by howetuft** [comment]
Hello @MisterMakerNL ,
Yes, thank you very much, I will mention it!
As you noticed, I wrote some doc about installation, which is, I think, a big obstacle for many users: if you have any other remarks, please let me know - I value much your opinion!

**Comment by luzpaz** [comment]
@howetuft maybe we should talk about how to trigger a CI to autobuild Cycles standalone (see https://github.com/MisterMakerNL/Cycles-stand-alone-windows-build/issues/1)

**Comment by howetuft** [comment]
@luzpaz That's a good idea, but I have absolutely no skill about that, and I don't practice Windows: what do you propose exactly?

**Comment by MisterMakerNL** [comment]
Can't wr just include cycles in the installation just like how FEM workbench includes calculus?

**Comment by luzpaz** [comment]
Perhaps @MisterMakerNL's approach makes more sense, right now. 

A usecase for building it via automation is if folks want to see 'chain of custody' of how cycles standalone is generated (instead of a black-box approach) then perhaps we can open a feature request?
