### ISSUE TITLE
Appleseed fails to load mesh files due to unescaped "\t" in windows temp path

### ISSUE THREAD

**Issue by lbfaps** [FreeCAD/FreeCAD-render#30]
On Windows appleseed fails to load the object files with following error message:
> failed to load mesh file c: emp\_i3busjne.obj: i/o error.
Thus interrupts the process with
> failed to load project file ...
Inspecting the project file reveals that there is an tab inserted between "c:" and the rest of the path.  Probably this is due to the unescaped character sequence "\t" in "c:\temp\...".

OS: Windows 10 Enterprise Version 10.0.14393
FreeCAD: 0.19.19758

Please tell me, if additional information is required.

**Comment by howetuft** [comment]
Hello,
Could you please provide the offending line in project file?
(should be something like:  `<parameter name="filename" value="[objfile_path]" />`)
Other question: which version of python do you use?

**Comment by lbfaps** [comment]
Hi,

on a simple sample project the offending line looks like:
```xml
<object name="_sh54wvsi" model="mesh_object">
   <parameter name="filename" value="c:	emp\_sh54wvsi.obj" />
</object>
```

I think it's related to lines 101 to 103 in Appleseed.py

I am running Python 3.7.3

**Comment by howetuft** [comment]
Hello,
Sorry, I have no Windows computer, so, despite my attempts, I am not able to reproduce and permanently fix the bug...
However, I may have a workaround to propose to you:
Indeed, the trouble comes from your temporary directory path "c:\temp", which is erroneously escaped to "c:<tab>emp", due to '\t' sequence.
So, I would propose you to change your temporary files directory to a path not containing '\t', (for instance "C:\mytemp"). Temporary files directory should be configurable somewhere in Windows parameters...

Let me know if it helps you. I'll try to explore your problem if I can get a Windows computer.

**Comment by lbfaps** [comment]
Hello,
thank you for investigating the issue. In my opinion, a simple code adjustment would be to replace lines 154ff. with
```python
</object_instance>""" % (colorname, color, alpha,
                                    bsdfname, colorname,
                                    matname, bsdfname,
                                    objfile, meshfile.replace('\', '\\'),
                                    objfile+"."+objname,
                                    objfile+"."+objname,
                                    matname, matname)
```
to escape any occassionally occuring tab or newline character in Windows paths. However, I do not know if this might have any negative impact on UNIX based systems.

As temporary fix I will go ahead and replace any path in the resulting file by search and replace instead of changing system variables for convenience reasons.

Thank you for your support!

**Comment by howetuft** [comment]
Good idea! I'll test it with Linux to avoid regression and give you a feedback.
Does it solve the issue on your Windows system?

**Comment by lbfaps** [comment]
Just tried it out and it solves the issue in my case without any noticable backdraw. Of course, it has to be only on dot in the code:
```python
</object_instance>""" % (colorname, color, alpha,
                                    bsdfname, colorname,
                                    matname, bsdfname,
                                    objfile, meshfile.encode('unicode_escape').decode('utf-8'),
                                    objfile+"."+objname,
                                    objfile+"."+objname,
                                    matname, matname)
```
But I am uncertain how encoding/decoding behaves if it comes to other languages. In my case german is not a problem. So should be english. But what about languages with "foreign" letters? What's the safest encoding?

**Comment by howetuft** [comment]
Hello,
I've tested it on my linux system and it works (no regression). I think there will be no trouble if temp file path does not contain any non-ascii characters. Thus I posted a PR based on your proposition: thanks!

**Comment by lbfaps** [comment]
Nice, thank you for your support!
