### ISSUE TITLE
[Contest]

### ISSUE THREAD

**Issue by MisterMakerNL** [FreeCAD/FreeCAD-render#313]
Just place this here for any wanderers that are interested into doing a contest. 
https://forum.freecad.org/viewtopic.php?t=81898

**Comment by luzpaz** [comment]
Is it a contest or challenge ?

**Comment by MisterMakerNL** [comment]
I mean I'll make a vote at the end.
Maybe the price is being on next splash-screen?

**Comment by howetuft** [comment]
Hello,
I close this topic...

**Comment by MisterMakerNL** [comment]
We will be back!
