### ISSUE TITLE
handling of links to std::part broken.

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#320]
adding a link to a std::part to a render-project pulls in the link-target too.
Two problems:

1. If you add the original and the link to the render-project (both should be rendered) you got two _originals_  on the same position, which leads to render-problems.

2. If you only add the link (because you do not want the link-target to be rendert), it get’s rendert.

**Comment by howetuft** [comment]
Hello,

Well, I'm not sure to see a problem in what you describe, but I may not fully understand your point.
Just to make things clear, I've written a small script you can copy/paste in the console:

```python
import Render

doc = App.newDocument()

# Create a part
cube = doc.addObject("Part::Box","Box")
cube.Label = "Cube"

# Create a link
link = doc.addObject('App::Link','Link')
link.setLink(cube)
link.Label = "CubeLink"
link.Placement.translate(App.Vector(15, 0, 0))

doc.recompute()

# Place point of view
Gui.activeView().viewDefaultOrientation()
Gui.runCommand('Std_PerspectiveCamera', 1)

# Create a Render Project (select your own renderer)
proj, _, _ = Render.Project.create(doc, renderer="Ospray", template="ospray_studio_light.sg")
# proj, _, _ = Render.Project.create(doc, renderer="Povray", template="povray_studio_light.pov")
# proj, _, _ = Render.Project.create(doc, renderer="Cycles", template="cycles_studio_light.pov")

# Add views
proj.add_view(cube)
proj.add_view(link)

# Render
proj.render()
```
Do we agree that, with such a script, we expect to see 2 cubes in the rendering (the original and the link)?

**Comment by howetuft** [comment]
OK, thank you, this is clearer, I'm gonna investigate.

**Comment by berberic2** [comment]
Fine.
To get the second problem, comment the `proj.add_view(part)` out. The part is rendered even it has not been added…

**Comment by howetuft** [comment]
Yes, you're right. Actually, the 'std part link' object has got a `Group` property, pointing to the underlying Cube. In such case, it is not clear for me how to handle it precisely: create views for all components + container, or for container only (I've already encountered both cases...).
Seems that 'links to App::part' should follow the second behaviour (container only), whereas they are currently defaulted to first one. I'm gonna fix it...

**Comment by howetuft** [comment]
Hello,
#322 should fix the problem, could you please confirm?

**Comment by berberic2** [comment]
Seems to work.
Thanks.

**Comment by howetuft** [comment]
Fine, thank you! I close the issue.
