### ISSUE TITLE
Merge #358 breaks workbench (init needs to be updated too to reflect removal of set_a2p)

### ISSUE THREAD

**Issue by brummbrum** [FreeCAD/FreeCAD-render#359]
https://github.com/FreeCAD/FreeCAD-render/pull/358 removes 'set_a2p' in utils.py. However, __init__.py still tries to import it, breaking the workbench upon load.

-> init needs to be updated too, i.e. remove import of set_a2p.

I tested this quickly by commenting it out and now the workbench loads properly.

Tested in FreeCAD 0.21.2

**Comment by howetuft** [comment]
Yes, you're right, thank you and my apologies. I removed the offending import from init.

**Comment by brummbrum** [comment]
Wow, that went fast :-) 
Thank you for making this workbench! I just got my toes wet with it using the luxcore renderer. Works great and so convenient to do everything directly out of Freecad. Will have to play with making custom templates soon. Merci!

**Comment by howetuft** [comment]
You're welcome! Thank you for reporting and have fun...
