### ISSUE TITLE
Does not start anymore with latest FreeCAD 0.22dev and Ondsel ES 2024.2 builds

### ISSUE THREAD

**Issue by NothanUmber** [FreeCAD/FreeCAD-render#402]
Getting the error message "DLL load failed while importing QtWebEngineWidgets: The module was not found" when trying to start the Render workbench. Getting the same error message in Ondsel 2024.2 and FreeCAD 0.22 (current build 37213).

**Comment by howetuft** [comment]
Hello,
Thank you for reporting!
Yes, FreeCAD core team removed QtWebEngine from dependencies shipped with 0.22 (with no consideration for workbenches using it). https://forum.freecad.org/viewtopic.php?p=757394#p757394

I'm gonna find a solution and I'll come back to you.

**Comment by howetuft** [comment]
Hello @NothanUmber,
It took me a while, but I think I've found a solution: #408. Could you tell me if it works for you please? Thanks!

**Comment by NothanUmber** [comment]
Hi @howetuft,
thank you for investigating! At least the previous error doesn't pop up anymore!
Now I get the following error when trying to load the Render workbench:
FreeCAD 0.22.0dev 37645, Render v2024.6.5
![grafik](https://github.com/FreeCAD/FreeCAD-render/assets/1221177/cd9395bd-7a31-473a-8af2-dcc386589823)

The Arch (BIM) workbench itself seems to load (using the version integrated with FreeCAD).

**Comment by howetuft** [comment]
Thank you for your feedback. This is yet another problem: the Material handling system has been (is being) completely overhauled in 0.22. It's presented as an improvement but, in reality, it breaks all the codes that used the historical version (including Render...). OK, I'm going to see what I can do to circumvent this issue...

**Comment by NothanUmber** [comment]
Thanks a lot - it starts now!
The "many empty windows" are still created (but on first sight they have no impact on functionality). General rendering of objects also works.
"Create material" seems to be greyed out for me (but that could also be because I don't have much experience with the Render workbench yet. Was just trying to follow your tutorial on Youtube (thanks for that!) and there it wasn't greyed out. Tried it with the Appleseed and the Ospray renderer.)
Here a screenshot that shows both the "empty windows" and the greyed out create material menu:
![grafik](https://github.com/FreeCAD/FreeCAD-render/assets/1221177/98761551-605a-411b-b90e-b636d80751ca)

**Comment by howetuft** [comment]
For "create material": Sorry, I copied/pasted some code from another workbench to fix the previous issue and there was a small bug. It should be fixed.

For the empty windows, could you please provide some more info:
- which OS do you use (Windows?)?
- when do the windows appear exactly? When you load the workbench, when you start a rendering...?
- in workbench Preferences, is the 'Enable multiprocessing' checkbox activated in 'Advanced & Debug' section?
- do they appear with plain FreeCAD or only with Ondsel?
- (any information you think pertinent to describe the issue...)
Thank you!

**Comment by NothanUmber** [comment]
* these screenshots were made with Windows 11 (x64)
* when loading the Render workbench
* no, I don't think so
* both FreeCAD and Ondsel, once the Render workbench is loaded
* just tried it on macOS (M2 Macbook with macOS 14.4.1) with Ondsel 2024.2.1, there these windows don't appear.

**Comment by NothanUmber** [comment]
correction to answer 2: the first two windows immediately open when starting the Render workbench. Then additional windows open when interacting with the FreeCAD UI with the Render Workbench being active. (Without loading the Render workbench in the first place the windows don't start to appear)

Also: The windows stay open when quitting FreeCAD. I have to close them manually.
When clicking on "settings" of one of these windows I see that they seem to be "Windows PowerShell" windows.

**Comment by howetuft** [comment]
Well, I don't manage to reproduce on my Windows PC.

However, if you search for "windows powershell keep opening", some answers evoke something about the task scheduler (example: https://answers.microsoft.com/en-us/windows/forum/all/windows-powershell-randomly-popping-up/05392abf-9869-4248-8e1f-85e919ab7504).
Could you check if that could be the cause of those spurious windows?

**Comment by NothanUmber** [comment]
Think I found the cause: When unloading ElevenClock (https://github.com/marticliment/ElevenClock) the problem is gone. Don't really need this anymore anyways, so uninstalling this is probably the easiest solution.

**Comment by NothanUmber** [comment]
Tested it with two different other Windows installations (both also Windows 11) and I was not able to reproduce the window issue. So it seems to be specific to this one Windows machine and something I will have to solve on my side.
Thanks a lot again for fixing the initial issue and for the Rendering Workbench in general!
I think we can close this issue.

**Comment by NothanUmber** [comment]
I think we can close this issue.
