### ISSUE TITLE
RUNTIME ERROR: Syntax error in texture name

### ISSUE THREAD

**Issue by ansorg** [FreeCAD/FreeCAD-render#406]
Hi,

I try to use render with FreeCad 0.21.2 and luxcore. 

I created a very basic examlple, followed the steps in the documentation but end up with this error. Using a material or not results in same error

![grafik](https://github.com/FreeCAD/FreeCAD-render/assets/3541784/9784663a-a4de-4207-9483-758f9fe70044)

I read that 0.22 is broken but 0.21.2 should work? What could be wrong?

**Comment by ansorg** [comment]
The corresponding line in project.scn is 
```
scene.materials.Unnamed#Part#Box.basecolor = nop 0.6120656199306977 0.6120656199306977 0.6120656199306977
```

**Comment by howetuft** [comment]
Hello,
Thank you for reporting!
What version of Luxcore do you use? Is it 2.6?

I attach a file that works fine on my system: can you tell me whether it runs on yours?
[LuxCore.zip](https://github.com/FreeCAD/FreeCAD-render/files/15366341/LuxCore.zip)

**Comment by ansorg** [comment]
My error! I use chocolatey to install as much as possible but the repo ony has v2.3 luxcore.

I have now manually installed v2.6 and no more errors. 

Thank you

**Comment by howetuft** [comment]
You're welcome
