### ISSUE TITLE
cycles studio-dark makes object dark

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#414]
![render](https://github.com/FreeCAD/FreeCAD-render/assets/13178920/65917d83-3bff-46d9-a2e6-9e74de707437)
[First row cycles, second row povray. 
 Columns: standard, sunlight, dark]

The cycles_studio_dark themes makes the object dark too. Not what I expected.
The cycles_sunlight and povray_sunlight make the object a blue tint (esp. cycles).

**Comment by howetuft** [comment]
Hello,
What is your version of Cycles?

**Comment by berberic2** [comment]
```
> ./cycles --version
4.0.0
```

**Comment by berberic2** [comment]
rebuild cycles from git (HEAD and v4.0.2). Still reports as 4.0.0 but works much better.
cycles_studio_dark looks good
cycles_sunlight still has slight blue tint (much better)

**Comment by howetuft** [comment]
API changed between 4.0.0 and 4.0.2, so I had to adapt the plugin. The output will not be correctly interpreted by previous version.

Please note that, as Cycles is not intended for production, developers can introduce major, non-backward-compatible changes to the API without warning .
My aim is to keep the plugin compatible with the latest version of the engine, so one has to make sure to keep the engine up-to-date...
