### ISSUE TITLE
Render-WB startup time

### ISSUE THREAD

**Issue by berberic2** [FreeCAD/FreeCAD-render#428]
I just realized that the render-wb costs about 7 seconds when starting FreeCAD, even it is not autoloaded and never used. That‘’s about an 58 % increase of startup-time (from about 12.45 s to about 19.75 s) if the render-WB is installed.
(All numbers are taken on my PC)

```
FreeCAD 0.22.0, Libs: 0.22.0devR38259 +2 (Git)
© Juergen Riegel, Werner Mayer, Yorik van Havre and others 2001-2024
FreeCAD is free and open-source software licensed under the terms of LGPL2+ license.
FreeCAD wouldn't be possible without FreeCAD community.
  #####                 ####  ###   ####  
  #                    #      # #   #   # 
  #     ##  #### ####  #     #   #  #   # 
  ####  # # #  # #  #  #     #####  #   # 
  #     #   #### ####  #    #     # #   # 
  #     #   #    #     #    #     # #   #  ##  ##  ##
  #     #   #### ####   ### #     # ####   ##  ##  ##

Sheet Metal workbench loaded
[Render][Init] Checking dependencies...
[Render][Init] Checking package 'PyQt6' - OK
[Render][Init] Checking package 'setuptools' - OK
[Render][Init] Checking package 'wheel' - OK
[Render][Init] Checking package 'renderplugin' - OK
[Render][Init] Checking package 'QtPy' - OK
[Render][Init] Checking package 'PyQt6-WebEngine' - OK
[Render][Init] Done.
```

**Comment by howetuft** [comment]
Hello,

> I just realized that the render-wb costs about 7 seconds when starting FreeCAD

Yes, Render initialization is longer than before, as it now has to install some dependencies (especially the ones that were removed from core FreeCAD). But there is a caching mechanism, so the overtime should only be a few seconds in standard run:

--> 7 seconds is not irrelevant; however is it a statistic based on several trials?

Moreover, Render kindly displays a few messages when it initializes, but not all workbenches do, and some may initialize silently at the same time, delaying the whole thing.

--> So, could you also record log messages, to track other WB simultaneous inits, and also include timecode for each entry? (see General > Report view in settings).

> even it is not autoloaded and never used.

No, Render initialization occurs only when the workbench is requested to do so. So there is something that requires it to load.

**Comment by MisterMakerNL** [comment]
There is actually an issue with the messages in the solashscreen that causes a delay: https://github.com/FreeCAD/FreeCAD/pull/15435

**Comment by berberic2** [comment]
The times are typical values from multiple startups.

I measured the time from starting FreeCAD (without any file) to the moment the GUI is shown.
The **only** difference between the 12is and 19is seconds starts is weather the render-WB is loaded.

The `[Render][Init]`-messages are shown during splash-screen, before the GUI is up.

And the render-WB is not loaded as the workbench-settings shows (after loading the `Laden`-button is replaced by a `Geladen` label)
![Screenshot_20240718_093948](https://github.com/user-attachments/assets/205d2808-d292-4d8a-bf94-f2fa70fa61b7)

**Comment by berberic2** [comment]
Attached are logs of freecad-startup with render-WB installed (not the first time render loads), freecad-startup without render-WB installed and the difference between the two (without timestamps).

If render-WB is installed, it gets initialized even if it should not autoload and it pulls the mesh-WB too.
This takes about 7 seconds (09:48:16 - 09:48:09 ≈ 0:00:07)

[Log-with-render.txt](https://github.com/user-attachments/files/16279705/Log-with-render.txt)
[Log-without-render.txt](https://github.com/user-attachments/files/16279707/Log-without-render.txt)
[Log-diff.txt](https://github.com/user-attachments/files/16279709/Log-diff.txt)

**Comment by berberic2** [comment]
> There is actually an issue with the messages in the splashscreen that causes a delay: [FreeCAD/FreeCAD#15435](https://github.com/FreeCAD/FreeCAD/pull/15435)

This patch results in reduced startup-time (about 25 %)  if the render-WB is not installed and consistently causes a core-dump during startup if the render-WB is installed.

**Comment by howetuft** [comment]
Thank you for the diff, very efficient.

> it pulls the mesh-WB too.

Indeed! And MeshPart as well, both being internal dependencies of Render. It seems to account at least for half of the init time (from 09:48:09 to 09:48:13). Not so much I can do about that, unfortunately...

For the other part, ie external dependencies, I've just removed 2 useless packages: it may help a little (please update the WB).


> And the render-WB is not loaded as the workbench-settings shows 

That's a mystery to me, as the log shows the contrary.


> consistently causes a core-dump during startup if the render-WB is installed.

Thank you for reporting. Another regression from 0.22... OK, I'm gonna try to file an issue upstream.

**Comment by berberic2** [comment]
> Indeed! And MeshPart as well, both being internal dependencies of Render. It seems to account at least for half of the init time (from 09:48:09 to 09:48:13).

I’m not sure about this.
```
09:48:09  Loading MeshPart module... done
09:48:09  Loading Mesh module... done
09:48:13  [Render][Init] Checking dependencies...
```
at 9:48:09 loading Mesh seems to be _completed_. The question is what takes the time (≈ 4s) until the first Render log-entry. This might as well be the render-WB.

**Comment by howetuft** [comment]
> This might as well be the render-WB

Good point. I reviewed the code and it appears that, among other dependencies, I need to import Assembly3. It takes at least 2 seconds on my PC. I've added log messages to materialize this, could you please check on your machine?

**Comment by berberic2** [comment]
```
19:58:13  [Render][Init] Starting Render initialization
19:58:13  [Render][Init] Importing 'Assembly3'
19:58:15  [Render][Init] Importing 'Assembly3'... done
19:58:15  Loading MeshPart module... done
19:58:15  Loading Mesh module... done
19:58:16  [Render][Init] Checking dependencies...
[…]
19:58:18  [Render][Init] Done.
```

Whatever you have done. It is about 2 s faster now with render-WB, so render-WB init is down to 5 s from 7 s. But it is still loaded when it shouldn’t.

**Comment by howetuft** [comment]
> Whatever you have done.

I pruned 2 unnecessary imports from previous versions.

 > render-WB init is down to 5 s from 7 s

That should be the best I can reach, I'm afraid.

> But it is still loaded when it shouldn’t.

Surprise: every workbench with a `InitGui.py` seems to be initialized at startup, whatever settings the user provides: https://github.com/FreeCAD/FreeCAD/blob/main/src/Gui/FreeCADGuiInit.py#L195

Having said that, well... there could be a solution with a minimal initialization in `InitGui.py`, but it may require some strong refactoring.

> consistently causes a core-dump during startup if the render-WB is installed.

I tried to reproduce (compiled FreeCAD 0.22 from sources with the patch) but I can't, actually. Is the crash systematic for you?

**Comment by berberic2** [comment]
> > render-WB init is down to 5 s from 7 s
> 
> That should be the best I can reach, I'm afraid.

That still is about a 30 % slowdown of startup with render-WB installed on my system…

> > consistently causes a core-dump during startup if the render-WB is installed.
> 
> I tried to reproduce (compiled FreeCAD 0.22 from sources with the patch) but I can't, actually. Is the crash systematic for you?

It was, but I only made about 4 tests with render installed and maybe 3 without.
Now it is no longer systematic.
With the patch, I get core-dumps during startup sometimes, independent of the render-WB.
Somewhere in the splashscreen code. Maybe a race-condition or insufficient locking of data, …

[segv.txt](https://github.com/user-attachments/files/16287852/segv.txt)

**Comment by berberic2** [comment]
Some more insight:
```
QPainter::begin: A paint device can only be painted by one painter at a time.
QPainter::setCompositionMode: Painter not active
QWidget::repaint: Recursive repaint detected
QBackingStore::endPaint() called with active painter; did you forget to destroy it or call QPainter::end() on it?
```

**Comment by howetuft** [comment]
> That still is about a 30 % slowdown of startup with render-WB installed on my system…

It is mainly due to dependencies, and also to the fact that FreeCAD initializes the workbench at start-up time, not at use time. The only thing I could do would be to split imports between immediate and delayable and have Render manage startup time/use time internally, with dynamic imports, but it's a pretty heavy refactoring of imports. I'll look at it later.

**Comment by berberic2** [comment]
I don’t know how it is meant to work. But the possibility to select for every workbench if it get’s autoloaded or not in the preferences seems not to make much sense if all workbenches get initialized anyway…

**Comment by howetuft** [comment]
I totally agree. Actually, FreeCAD requires the workbenches to initialize during startup but, during this initialization, the workbenches are not supposed to load themselves. It's pretty subtle.

**Comment by berberic2** [comment]
The segv seems to result from `src/Gui/GuiApplication.cpp::GUIApplication::notify()`

`GUIApplication::notify()` seems to be being interrupted by a call to `GUIApplication::notify() `
Maybe two threads calling `GUIApplication::notify()` without proper locks?

**Comment by howetuft** [comment]
> Maybe two threads calling GUIApplication::notify() without proper locks?

Yes, it smells like a race condition.

**Comment by howetuft** [comment]
@berberic2 
I've made some refactoring on Render initialization: you should now experience a much faster start-up, if the workbench is not autoloaded. Could you please confirm?

**Comment by berberic2** [comment]
Hmm…
A quick test (render v2024.1.23):

without render: about 11,1 s
with render without autoload: about 16,3 s
with render with autoload: about 16,2 s

**Comment by howetuft** [comment]
is it dev branch?

**Comment by howetuft** [comment]
And current Render version is 2024.7.4

**Comment by berberic2** [comment]
O.K. It’s confusing in the plugin-manager:
![Screenshot_20240723_230004](https://github.com/user-attachments/assets/376c3c8d-44cf-4e76-a3ef-b2cc38f60bef)

**Comment by berberic2** [comment]
> is it dev branch?

FreeCAD?
That’s from git, 
```
OS: Debian GNU/Linux 12 (bookworm) (KDE/plasma)
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38259 +2 (Git)
Build type: Release
Branch: Meins
Hash: cca7ec56c09f1b5e8c9ccd9328066c3277a31d7d
Python 3.11.2, Qt 5.15.8, Coin 4.0.0, Vtk 9.1.0, OCC 7.6.3
Locale: German/Germany (de_DE)
Installed mods: 
  * Assembly4 0.50.15
  * sheetmetal 0.4.23
  * Silk 0.1.5
  * CurvedShapes 1.0.9
  * DynamicData 2.62.0
  * FreeCAD_assembly3 0.11.3
  * fcgear 1.0.0
  * fasteners 0.5.24
  * QuickMeasure 2022.10.28
  * ExplodedAssembly
  * Curves 0.6.42
  * Pyramids-and-Polyhedrons
  * Render 2024.7.4

```

**Comment by howetuft** [comment]
I mean _Render_'s `dev` branch (I try not to push directly to master). You should be able to change branch in the addon manager (upper right corner):

![1721768795](https://github.com/user-attachments/assets/ef160ba4-efd7-4ece-8aee-9da80cda9cc0)

**Comment by berberic2** [comment]
without render: about 11,1 s
with render without autoload: about 11,2 s
with render with autoload: about 12,1 s

**Comment by howetuft** [comment]
Happy?

**Comment by berberic2** [comment]
Yes. That’s fine.
Interesting is the small difference between with and without autoload.

**Comment by howetuft** [comment]
> Yes. That’s fine.

Thank you

> Interesting is the small difference between with and without autoload.

Yes, there is a (small) residual time, due to unavoidable remaining initializations (and maybe some loading code on FreeCAD side)

If you're OK with that, can you please close the issue?

**Comment by berberic2** [comment]
Yes sure :)
