### ISSUE TITLE
PathTwistedArray and PathLinkArray tools (Draft WB)

### ISSUE THREAD

**Issue by Francisco-Rosa** [FreeCAD/FreeCAD-render#444]
I've been working with the _PathArray_ tool (Draft WB) and I encountered a rendering problem when I used its linked mode (_PathLinkArray_). I created a test file to send, but the issue didn't appear (it seems to be intermittent). However, when testing _PathTwistedArray_ the same issue appears, but constantly: only some parts are rendered.

https://forum.freecad.org/viewtopic.php?t=55297&hilit=Render+cycles&start=140

In the past, I had the same concern with _Draft_ArrayTools_ in its Link option. I mention this because the problems may be related in some way.

**Comment by howetuft** [comment]
Hello,
#447 may fix the problem. Could you please test and give me some feedback?
Caveat: the commit is on the `dev` branch
