### ISSUE TITLE
Render issue with A2Plus WB

### ISSUE THREAD

**Issue by 777Raim** [FreeCAD/FreeCAD-render#448]
Hello!

I have an assemble project with parts. Some parts are imported to project via `Add shapes from an external file` at A2Plus WB,

![Screenshot from 2024-09-05 14-01-23](https://github.com/user-attachments/assets/22d4a694-9956-4814-b80e-8ac630602491)

because this parts has inside 2 parts: normal and mirrored (I make this, because it's easier to modify main part and don't make same steps to apply same modifications at mirrored part)

![Screenshot from 2024-09-05 14-06-19](https://github.com/user-attachments/assets/8a5f8d81-97c2-4708-8ca0-56d6770ecf60)

So, if I try to Render that project, at the render image I have mirrored parts like normal (it's like they be flipped).

![1](https://github.com/user-attachments/assets/fb3e6ba9-f7ba-47df-95c7-24cb3d4ea2f8)

Thanks!

p.s. Yes, I can make the assemble with single parts to make Render works, but it more difficult to make corrections while modelling.

**Comment by howetuft** [comment]
Hello,
Would it be possible to provide me an example file, please? It would be easier for me to debug... Thank you!

**Comment by 777Raim** [comment]
Hello!

[Here](https://drive.google.com/file/d/1pzjxzFLNM_nI6s2WMVL5AAa_oe1MTUTV/view?usp=sharing) the `Test Project`

**Comment by howetuft** [comment]
Thank you! I'm not very familiar with A2P: how did you get the mirroring transformation?

**Comment by 777Raim** [comment]
Will try to explain:

1. I have a model (Left orientation) made at `Part Design` WB.
![Screenshot from 2024-09-07 12-53-30](https://github.com/user-attachments/assets/936f1bf6-7d7f-4db3-b0a5-5383bb79e69c)
2. Go to `Part` WB and apply `Mirroring` modificator.
![Screenshot from 2024-09-07 12-54-13](https://github.com/user-attachments/assets/8e7c3e75-6c14-4512-a140-60462e4ef3dd)
3. I get 2 models: `Left` and `Right` (mirrored) orientations.
![Screenshot from 2024-09-07 12-54-56](https://github.com/user-attachments/assets/4cacfc9b-4131-48cb-a2ca-6b20b401808f)
Rename `Mirrored` model to `Right` to simplify.
![Screenshot from 2024-09-07 12-55-16](https://github.com/user-attachments/assets/9cd04c4f-e035-41a8-a375-e91d48970fdc)
4. Now at `A2plus` WB add parts of model via `Add shapes from an external file`
Add `Left` part of model
![Screenshot from 2024-09-07 12-55-40](https://github.com/user-attachments/assets/7ea43c5a-3628-4678-8e04-c23016eac775)
![Screenshot from 2024-09-07 12-56-08](https://github.com/user-attachments/assets/b4020feb-ba73-4c2d-9dd7-c4de45936765)
Add `Right` part of model
![Screenshot from 2024-09-07 12-56-27](https://github.com/user-attachments/assets/389b522b-8347-4dec-b7c9-47f74005c248)
![Screenshot from 2024-09-07 12-56-34](https://github.com/user-attachments/assets/3904171c-a418-4390-9006-5aeead93c905)
5. And now I have 2 `Parts` of `Model` at `A2plus` WB Assemble project
![Screenshot from 2024-09-07 12-57-14](https://github.com/user-attachments/assets/10d687dd-3075-41b6-af56-fc8ebe29a26b)

**Comment by howetuft** [comment]
Hello,
I made a fix, it's on Render `dev` branch, if you want to try...

**Comment by 777Raim** [comment]
Hello! Thanks! All works as expected!

![Project_output](https://github.com/user-attachments/assets/492d937a-392c-4fa3-a470-9a78ead9b4ff)

**Comment by howetuft** [comment]
Fine! Thank you
