### ISSUE TITLE
Is there exisiting documentation on how Addon developers can integrate RenderWB into their workbenches?

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#454]
As being discussed in https://github.com/rostskadat/FreeCAD-SH3D/issues/5 is there documentation that said devs can reference ?
Usercases:  
* Adding RenderWB as an optional dependency into their [package.xml](https://wiki.freecad.org/Package_Metadata#.3Cdepend.3E) (Note: the syntax below is untested.)
```xml
<!-- Optional install of 3rd-party Render WB to streamline ability to render scenes using various rendering engines -->
<depend type="addon" optional="true">Render Workbench</depend>`
```
* How to add button to their workbench toolbar that directly call RenderWB functionality and circumvent the need to switch into RenderWB itself.
* ...(other usecases I can't think of ATM

**Comment by howetuft** [comment]
There is a complete API to interact programmatically with Render. Movie WB uses it, for instance. This API is not documented per se, but all modules, all objects and all attributes in Render have a docstring and I take a special care to write PEP-8 compliant code, to keep it as understandable as possible.
So it's possible to recreate Render buttons in other WB.

That being said, I'm not convinced there is a need for such a tight integration.

Some workbenches (the vast majority) create models in FreeCAD:
- BIM
- SH3D  
- Assemblies
- Etc.

Some others export them to rendering tools:
- Render
- Pov-ray
- Mesh export macros

The glu to connect them is just FreeCAD!

**Comment by luzpaz** [comment]
Fair. What about the first bullet point ?

**Comment by howetuft** [comment]
Oh yes! The first bullet is relevant indeed: workbenches with special needs in terms of rendering could reference Render as an optional dependency in their `package.xml`

**Comment by luzpaz** [comment]
> Oh yes! The first bullet is relevant indeed: workbenches with special needs in terms of rendering could reference Render as an optional dependency in their package.xml

@howetuft did you mention this somewhere ?
