### ISSUE TITLE
Array from Draft WB not rendering

### ISSUE THREAD

**Issue by IDDQDesnik** [FreeCAD/FreeCAD-render#464]
OS: Windows 10 build 19045
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: releases/FreeCAD-0-21
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.3
Locale: Russian/Russia (ru_RU)
Installed mods: 
  * Render 2024.11.22
  * SearchBar 1.1.0
  

![изображение](https://github.com/user-attachments/assets/7f2a844f-9bc7-4839-8a4b-cf6f17b9c62f)
![изображение](https://github.com/user-attachments/assets/43fb9a84-468b-415b-ac5c-f7232c066a6c)
[test.FCStd.zip](https://github.com/user-attachments/files/17958408/test.FCStd.zip)

**Comment by howetuft** [comment]
Hello,
Thank you for reporting! Should be fixed now: #467. Can you confirm?

**Comment by IDDQDesnik** [comment]
Hello,
Yes, now Array work fine. Thank you for quick fix.
