### ISSUE TITLE
No rendering starts even with LuxCoreRender or Appleseed

### ISSUE THREAD

**Issue by matbgn** [FreeCAD/FreeCAD-render#53]
## Expected behavior 
- Start of rendering when clicking on perform the render button and project selected.

## Actual behavior
- No rendering starts even with LuxCoreRender or Appleseed

## Steps to reproduce the problem
- Create a simple cube in Part for instance
- Give it a material in appearance (for instance stone)
- Switch to Render studio
- Create a LuxRender project 
- Select luxrender_standard.lxs
- Create a cam from actual position
- Select the cube and create a render view from it
- Select the LuxRender project and click on render button
- Find out that nothing is happening

## Specifications like the version of the project, operating system, or hardware
- FreeCAD version: 0.18.4
- OS: Windows 10
- Version: 10.0.17763 Build 17763
- Processor: Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz, 2712 Mhz, 4 Core(s), 8 Logical Processor(s)
- RAM: 16 GB
- LuxCoreRender version: Standalone release v2.3
Also tried with:
- Appleseed version: 2.1.0-beta

## Report view
```
'PartDesign.Feature' object has no attribute 'Visibility'Running the Python command 'Render' failed:
Traceback (most recent call last):
  File "C:\Users\MBorgognon\AppData\Roaming\FreeCAD\Mod\Render\Render.py", line 1095, in Activated
    project.Proxy.render()
  File "C:\Users\MBorgognon\AppData\Roaming\FreeCAD\Mod\Render\Render.py", line 422, in render
    objstrings = [get_rdr_string(v) for v in views if v.Source.Visibility]
  File "C:\Users\MBorgognon\AppData\Roaming\FreeCAD\Mod\Render\Render.py", line 422, in <listcomp>
    objstrings = [get_rdr_string(v) for v in views if v.Source.Visibility]

'PrimitivePy' object has no attribute 'Visibility'
```

**Comment by howetuft** [comment]
Hello @matbgn,
Thank you for using Render workbench and for your feedback!
I think there is an issue between version 0.18 and new visibility support I introduced a few days ago (commit 8f02cb15a9cdec2324fead14ccdd3c3103534e21), as I develop and test with 0.19.
Thus, as a workaround, I temporarily disabled visibility support (I'll fix the bug later).
Can you tell me if it works for you? Thanks in advance...

**Comment by matbgn** [comment]
Simply like a charm ❤️ 

Many thx¨!
