### ISSUE TITLE
Materials implementation

### ISSUE THREAD

**Issue by ghost** [FreeCAD/FreeCAD-render#64]
(continued from #38 )
@howetuft 

I agree the material setup should be simple for rendering. We could take diffuse color from the already existing entry in the material card in freecad and turn it into a material for all renderers. If they define an IOR, we could also assume they mean a glass and use some default values for the renderer's glass material.

I also don't think we should deprive users from customizing their materials any further. This includes allowing them to specify renderer specific material properties.

Each renderer has specific material properties not really shared by other renderers. This has to do with how the renderer works internally and I haven't found a way to specify something more generally that would include all possible algorithms with their parameters. Let alone the existing "simple ones" currently used by the renderers we support.

I propose if the user wants to input specific parameters for their materials for a renderer, we should allow them. If it's not there, we'll fall back on standard values.

**Comment by howetuft** [comment]
Thank you for your proposition. I've got 2 reactions and a point of discussion:

> I also don't think we should deprive users from customizing their materials any further. This includes allowing them to specify renderer specific material properties.

I agree with you. We could then have 2 levels of access to the material properties:
- Basic: uses a simple renderer-independent set of parameters for a given material, providing also default values. For instance, for glass: color, IOR (default being for instance: white, 1.5).
- Advanced: allows user to add some renderer-specific settings to the material.

> If they define an IOR, we could also assume they mean a glass
Well, I'm not very fan of this idea. Inferring material type from attributes can be error-prone, could also lead to heterogeneous behaviors between renderers. I think the material should carry a rendering material type information, explicit for the renderer.



My main point of discussion is:
Eventually, I really wonder if we should use material card for material rendering. I've got a limited understanding of FreeCAD Material, but to me material card seems to be designed mainly for physics (FEM etc.) and appears to have some penalizing constraints for rendering:
- FreeCAD materials have subdivisions according to their mechanical properties, for the same rendering result. For instance, there are dozens of 'Steels' in FreeCAD materials. If we used material card, would we have to repeat the same rendering settings dozens of times?
- to the contrary, some FEM materials should be subdivided from the rendering point of view: glass/rough glass etc. Should we subdivide FreeCAD materials with their rendering shades?
- some rendering materials could not be defined via a FreeCAD Material, as they've got no actual physics: Disney, emission, fur, cloth...

My proposition would be to create a RenderingMaterial class in the workbench (like lights and camera classes...), renderer-oriented, carrying the attributes we need. 
This class would be instantiated as material objects in the project and the workbench would provide a way to apply/link such materials to an object. At rendering time, the RenderingMaterial object would be passed to the renderer with the mesh, up to the renderer plugin to translate it into SDL.
We would propose a library of predefined rendering materials, to instantiate the class: glass, car paint, matte, emission, metal...
Moreover, this way, we could also provide a "pass-through" material, with which the user could directly write a material into renderer SDL, that would be passed without alteration to the renderer. 
And, if no RenderingMaterial is provided for a mesh, we could fall back to its FreeCAD material properties (or white matte, if no material is provided...)

It would thus combine a simple approach with standard materials, a powerful one with fully-customizable material and a fallback to general FreeCAD material approach...

What do you think about that?

**Comment by justnope** [comment]
> This class would be instantiated as material objects in the project and the workbench would provide a way to apply/link such materials objecs to FreeCAD objects.

Would you change your mind if @yorikvanhavre already approved of using custom attributes in the material chart in this way?

**Comment by howetuft** [comment]
Well, this could help, but there would be still some critical questions to address, if we stick to material card:

- How to store rendering parameters once, for FreeCAD materials having multiple physical declinations? For instance, common rendering parameters for the Steel-* materials (I've counted more than 90 declinations of Steel in v0.18...)
- How to deal with rendering materials relinked to no physical ones? For instance : Disney
- How to deal with objects having a core material different from their rendering material? For instance a part made of Steel (core), but that should be rendered with Car paint (external appearance).
- How to provide multiple rendering shades for a single FreeCAD material (may be the same question as previous one)? For instance: polished/rough/oxydized copper (all of that being copper for physics), or polished/rough glass etc...
- How to add renderer-specific settings? For instance, specifying some glass is 'archglass' for Luxcore
- How could we implement a pass-through rendering material feature, to make user able to specify complex rendering material directly in SDL?

To me, a separate RenderingMaterial would solve that (and we could fall back to material card if no such RM is provided), but I'm looking forward for your ideas...

**Comment by howetuft** [comment]
And one question more:

- Once the user has selected a material, how can he tune one the default parameters? For instance, how to tune color parameter for a glass material?

**Comment by howetuft** [comment]
Another thought:
If we use the material card, we could focus it on the Disney material. It is very versatile (I think all common materials, like glass, metals, paints etc. can be represented) and widely implemented (at least in Cycles, LuxCore, Appleseed, Mitsuba...)

**Comment by justnope** [comment]
I've thought about it and I think it might not matter that much where the data is stored.

We implement a class from which the underlying the renderer implementation can get their data from. If we later on switch from a RenderingMaterial backed store to a freecad material store, the changes would only be in that class and no code needs to change for the various renderers.

I think in the end we're going to need that class anyways. I'm thinking more about the uses in architectural design and how we keep forgetting about our color blind friends. If we use a class to get, for example, color data, we can add a color transform for the various types of color blindness and see how they will perceive it.

**Comment by justnope** [comment]
> How to deal with rendering materials relinked to no physical ones? For instance : Disney

All rendering techniques are an approximation. For example, appleseed has a parameter to add energy losses due to the approximation used in their micro surface calculations. A real renderer would use quantum field equations to render, but no one is doing that for obvious reasons.

**Comment by howetuft** [comment]
> What about walls which are painted with one color on one side but a different one on the other side...

The only idea I find now, as a first step, is to have the user create two facings for the wall...

> We implement a class from which the underlying the renderer implementation can get their data from. 

Yes! But I would also propose the following:
- If an object has no RenderingMaterial, we could fall back to its material card's rendering parameters
- And we could make those material card's rendering parameters map to Disney (PBR) parameters (it may require to add some parameters in the card), and send a Disney material to renderer.
This way, we keep in touch with FreeCAD material system, if it is improved in the future.

I propose you to start writing some code, to expand the concepts... I have created a **'materials' branch** where we can do some prototyping without altering the master at this stage - to be merged when we've got something operational. Please feel free to send PRs to this branch! (just comply to PEP8 please)

**Comment by justnope** [comment]
> (just comply to PEP8 please)

I'd be more than happy to comply with PEP8. At least now there's a standard. Previously I tried to emulate what I thought the conventions were, only to discover at the end of the file they used a new convention.

Anyways, back to material thing. The disney shader is actually a bad example because even this standarized example got mutilated by a renderer. The disney shader doesn't render glass-like materials, but cycles (blender) extended the definition and added parameters for glass.

What I'm saying is that classifying a material according to shader doesn't help that much unless we take the underlying renderer into account. So for every renderer, except cycles, a material with IOR could be classified as a non-disney glass-like shader, while for cycles I'm not sure if there's a separate material class for glass or if everything got lumped into that disney shader.

I've tried to combine the parameters of the different materials and different renderers and came to the conclusion that it couldn't be done. The renderers are too different and the parameters with the same names might not be compatible.

I'm leaving out the entire discussion about color spaces (linear RGB, sRGB, ...) because it's not relevant enough at the moment.

What I'm proposing a class with a sort of namespace based material lookup. If, for example, the appleseed renderer looks up the material type. It first looks if the user defined an attribute "appleseed_materialtype" (or whatever and where ever). If it doesn't find it, it looks if an IOR has been defined and selects a glass material, otherwise the disney shader with a diffuse color from the material card is selected.

Keep in mind that the disney shader is the exception! It's the only shader that's popular enough to be shared amongst renderers. All the other shaders are not.

**Comment by howetuft** [comment]
> It first looks if the user defined an attribute "appleseed_materialtype" (or whatever and where ever). If it doesn't find it, it looks if an IOR has been defined and selects a glass material, otherwise the disney shader with a diffuse color from the material card is selected.

Sounds good to me!

**Comment by yorikvanhavre** [comment]
Totally agree with both.

1) is already implemented (but not yet very correctly used) - see https://github.com/FreeCAD/FreeCAD/blob/master/src/Mod/Material/StandardMaterial/Concrete-EN-C35_45.FCMat it has a "Father" property which, in theory, you should fill with another, existing material. There is still quite some work needed on those material cards ;) That way you can build complete hierarchies. And, indeed, the idea is that is a property is omitted in a material, you could go up to parents to retrieve that value.

2) I think we could have a [Render] category, with generic renderer-agnostic properties such as diffuse color, bump map, etc... and maybe additional [Cycles], [Luxrender], etc... categories with render-specific properties, if any. In any case, yes, we should start building a list. If you look at https://wiki.freecadweb.org/Material there is already a list in [Graphical], but I'm not sure it wouldn't be better to not consider this Graphical section (I haven't seen it really used anywhere yet), and to create our own Render section.

In any case, again, I think everything should "just work" with the bare minimum, basically we just need a color. Then, the more the material provides, the finer the render works...

**Comment by justnope** [comment]
> to model our parameters on those of Blender's Principled BSDF

Why and how did you make the decision to base it on Blender's shader?

Here's some background on the disney shader:
A paper describing the parameters of [the disney shader](https://disney-animation.s3.amazonaws.com/library/s2012_pbs_disney_brdf_notes_v2.pdf)

Here's the description of the extra parameters [blender](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html) added.

**Comment by yorikvanhavre** [comment]
both look similar.. I'm sure we can get a common ground here.

**Comment by howetuft** [comment]
@justnope my idea was not to use Disney as a catch-all, but as a fallback, to complete your previous proposition:

> It first looks if the user defined an attribute "appleseed_materialtype" (or whatever and where ever). [...] otherwise the disney shader with a diffuse color from the material card is selected. 

That's it. But, instead "the disney shader with a diffuse color", we would have a complete disney parameters set in the material card, to act as a fallback (baseColor, subsurface, metallic, specular, specularTint, roughness, anisotropic, sheen,  sheenTint, clearcoat), so it will be "the disney shader with the fallback parameters".

So, the workflow to get a material would be:
1°) the workbench looks for a renderer-specific material definition in the material card (your proposition). It can be a set of rendering parameters (like appleseed_materialtype, appleseed_ior etc.) or a pass-through string (appleseed_passthrough, my proposal).
2°) if none is present, it looks for the standardized disney set of parameters in the material card (baseColor, subsurface, metallic, specular, specularTint, roughness, anisotropic, sheen, sheenTint, clearcoat)
3°) if empty or not usable, it falls back to white matte.

What do you think about that?

**Comment by justnope** [comment]
@howetuft You are more talented than me in python. I've implemented a class that allows to extract color, floating point, etc... data from the freecad material dictionary. I know you can improve upon it.

Here's my amateurish attempt to get render specific data from the general material dictionary:

Github commit which abstracts it: [material helper]( https://github.com/FreeCAD/FreeCAD-render/pull/17/commits/abcdd1ce2e2cd8d9426d08302e64c2d1e165cf6c )

**Comment by howetuft** [comment]
Thank you. Well, some remarks:
- Your code is based on an outdated version of FreeCAD/Render, so it is very difficult to evaluate what you propose in current context. You have to rebase your code on current master before submitting (see here: https://wiki.freecadweb.org/Source_code_management#Rebasing_from_upstream).
- Your string operations should be improved/refactored. In particular, repeated string concatenation (operator +) is not recommended in Python, as string is immutable (https://softwareengineering.stackexchange.com/questions/304445/why-is-s-better-than-for-concatenation); moreover, readability of such code is questionable. Instead, you should use string formatting and Format Specification Mini-Language (see here https://docs.python.org/3/library/string.html#formatstrings) to generate pieces of SDL, for instance for matdef. You can look at plugins' current code for examples.
- I don't find your MaterialHelper class much useful as-is, as it appears just as a string formatting wrapper around material class. That job should be done inline by plugins - see previous point. However, a MaterialHelper would be useful to implement the *logic*: for instance, the fallback logic, the material inheritance mechanisms... Indeed, what we send to renderer plugin as a material should just be a dictionary (parameter name/parameter value), and it should be the job of the MaterialHelper to build this dictionary from FreeCAD materials system, looking in the right material cards sections, taking account of material inheritance, fallbacks etc. which we described previously.

**Comment by justnope** [comment]
Ok no probs
I think you're better suited to implement it than me

**Comment by justnope** [comment]
I'm not as proficient in python as you. You should have more than enough info to implement materials on your own

**Comment by howetuft** [comment]
Hello Justnope,
Sorry not to be reactive, I was AFK this week, plenty work.
I take the point and I shall surely deliver something about materials this summer.

**Comment by howetuft** [comment]
To those who are still alive in this thread:

Hello!

@yorikvanhavre wrote:
> The kind of workflow I imagine:
>
>  The user builds their model
>     They attribute or create basic materials to objects, from builtin cards or not, maybe not all objects
>     They switch to the Render WB
>     They create a Render project
>     If a render view has no material directly associated, the associated object is searched for a material (so for the user it doesn't matter if the material is associated to the base object or the render view)
>     If an object has no material, a default material is created on the fly from the color, at render time (like it does now)
>     If an object has a material, a material is created on the fly from it, at render time. Information not present in the material get a default value
>     Users can create and edit any material in a special editor which only edits render-specific values and saves them into the material

**I finally made all of that, it is in Materials branch!**

At now, I've implemented Diffuse, Glass and Disney materials and a pass-through system to send a material written in SDL directly to renderer (in addition to fallback capabilities). It is easily extendable to other kinds of mats, like glossy etc. I will add more in the future.


I made some tests on 'Villa Savoye' model, especially illustrating glass material (but using also Disney and Diffuse):

Appleseed:
![Appleseed](https://user-images.githubusercontent.com/34142192/93132953-c2cefa00-f6d6-11ea-8b52-db22b5b13cc3.png)

Cycles:
![Cycles](https://user-images.githubusercontent.com/34142192/93133282-412b9c00-f6d7-11ea-9792-5e33333749f1.png)

Luxcore:
![Luxcore](https://user-images.githubusercontent.com/34142192/93133291-4557b980-f6d7-11ea-9559-7ae18ecb82bb.png)

Povray
![Povray](https://user-images.githubusercontent.com/34142192/93133306-4b4d9a80-f6d7-11ea-85db-9625c32931f3.png)

And the real building:
![Villa_Savoye_en_2014](https://user-images.githubusercontent.com/34142192/93133978-55bc6400-f6d8-11ea-8869-12aad905ebf7.jpg)


I added some documentation [here](https://github.com/FreeCAD/FreeCAD-render/blob/materials/docs/Materials.md)

I'll merge to master in a couple of days. Until that, any comments are welcome!
