### ISSUE TITLE
luxcore doesn't work well with FC

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#7]
http://forums.luxcorerender.org/viewtopic.php?t=895

**Comment by yorikvanhavre** [comment]
It's hard to know what's wrong on what there is to fix or even if there something to fix from the forum thread... But let's leave it open so more reports can come

**Comment by justnope** [comment]
@luzpaz are you still having issues with the latest luxcorerender?
If so, I've implemented the new file format of luxcore in my branch. If you're willing to try it out to see if it resolves the issues...

**Comment by luzpaz** [comment]
justnope, not me, it was a link to their forum I found.

**Comment by luzpaz** [comment]
upstream announces 2.2 released  
https://forums.luxcorerender.org/viewtopic.php?f=9&t=1455&sid=aa0e4b42e2699f9a9e8fe2fa09651765

**Comment by howetuft** [comment]
Closed: Luxcore is now fully supported by Render (and Luxrender has been deprecated...).
