### ISSUE TITLE
Error when switching to Render Workbench

### ISSUE THREAD

**Issue by reneaye** [FreeCAD/FreeCAD-render#79]
After installing FreeCAD-render manually or with Addon Manager I got an error popup when switching to Render workbench:

Title: Error on switching workbench (Translated from german) 
Message: Expected maxsize to be an integer or None

Furthermore there is no Render tab in the settings section. 

FreeCAD v0.18
Win 10

**Comment by luzpaz** [comment]
Try installing [v0.19](https://github.com/FreeCAD/FreeCAD/releases/tag/0.19_pre) and reporting back.  
Please always post your FreeCAD [About](https://wiki.freecadweb.org/About) info.

**Comment by howetuft** [comment]
@reneaye Hello,
This is same issue as #78. I'll apply a patch tomorrow, if you can wait till that ; if you cannot, there is a workaround in the previous issue...

**Comment by reneaye** [comment]
Ah, didn't see that other issue #78 .
And yes, with 0.19 it works.
Thank you for the quick response.

**Comment by howetuft** [comment]
I applied a patch (PR #80), we should get rid of that even in 0.18
