### ISSUE TITLE
README: have more explicit instructions on how to use WB instead of referring to Raytracing

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#82]
![image](https://user-images.githubusercontent.com/4140247/94365415-d860fe00-009e-11eb-9cb2-0a2e5b0251f7.png)

How about a step-by-step set of instructions to make this super easy to understand and follow?

**Comment by howetuft** [comment]
I fully agree with you: user documentation could definitely be improved, explaining the Render process step-by-step:
- Installing and setting up the renderers
- Creating a project & adding the objects to render
- Setting up the camera
- Lighting the scene
(- Tuning the materials: I've already tried to do something about that)
- Launching external rendering

The README could present the general process, in a 'quick start' manner, and each step could be fully detailed in a dedicated MD file (stored in 'docs' subdir).

**Comment by luzpaz** [comment]
You can also use [collapsible divs](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab) in the README and fit all that info in one place

**Comment by howetuft** [comment]
Dear @luzpaz,
Following your sensible remark, I'm going to take a break from coding to write some user documentation.
I've noticed your suggestion about collapsible divisions; however, I still don't feel comfortable to add all the documentation into README.md, for two reasons at least: 1°) It would create a very fat and awkward file ; 2°) whatever stuff I add in README.md, there will be cluttered files around, as pictures cannot be directly embedded in markdown.
Therefore I shall first create separate files; but as these files can be merged into README via copy-paste in the future, there is nothing irreversible...

**Comment by howetuft** [comment]
Hello @luzpaz 
I did some documentation work as suggested above: described a quick-start mode, explained installation, wrote some missing documentation on various features...
I would value your feedback a lot... Thanks!
