### ISSUE TITLE
Decide how to utilize the FreeCAD wiki Render Workbench page

### ISSUE THREAD

**Issue by luzpaz** [FreeCAD/FreeCAD-render#90]
https://wiki.freecadweb.org/Render_Workbench  
It needs to be re-written...but maybe just in summary and linking to the documentation on this repo...?

**Comment by howetuft** [comment]
> maybe just in summary and linking to the documentation on this repo

Yes, fully agree. The wiki page is obsolete, it refers to an implementation which was never completed, and its name is confusing: it would better point to the present repo.

**Comment by luzpaz** [comment]
Maybe we need to mark sections of it obsolete or rename it and keep it for archival purposes. Lets ask @yorikvanhavre his opinion

**Comment by howetuft** [comment]
Hello,
I eventually created a wiki page for Render!
https://wiki.freecad.org/Render_Workbench
So we may close this long lasting issue...
